import type { SupabaseClient } from "@supabase/supabase-js";
import { supabase } from "@/integrations/supabase/client";
import { getClientEnv, isSupabaseConfigured } from "@/lib/config/env";

// Adapter over Lovable's generated browser client.
//
// `src/integrations/supabase/client.ts` is generated by Lovable's Supabase
// integration and carries a "do not edit it directly" banner. This module gives
// the auth, content, puzzle and journey repositories a stable import that does
// not depend on the generated file's shape — if Lovable regenerates its client,
// only this file has to follow.
//
// There is exactly ONE browser client in the app: the lazy proxy exported by
// the generated module. This adapter does not create a second one.
//
// Privileged server access lives in `@/integrations/supabase/client.server.ts`
// (service role, server-only). Never import that here, nor from any module the
// browser bundle can reach.

export { isSupabaseConfigured };

/**
 * The app's Supabase client.
 *
 * The generated client is a lazy Proxy: it constructs on first property access
 * and throws when the environment is missing. Callers that must tolerate an
 * unconfigured environment check `isSupabaseConfigured()` first — that is what
 * keeps the prototype UI rendering with no env vars set.
 */
export function getSupabaseClient(): SupabaseClient {
  return supabase as unknown as SupabaseClient;
}

/** The configured project URL, for diagnostics. Never returns a key. */
export function getSupabaseProjectUrl(): string | undefined {
  return getClientEnv().VITE_SUPABASE_URL;
}
