import {
  fromRows,
  pathOf,
  placementCells,
  type Grid,
  type Placement,
  type Selection,
} from "../grid";
import { validateSelection, type ValidationResult } from "../validation-service";
import { validateGrid } from "./mutable-grid";
import type { MutableGrid } from "./types";

// Solution handling and server-side verification.
//
// The rule this module exists to enforce: a client's claim that it finished a
// puzzle is evidence, not proof. Every completion is re-derived from the stored
// puzzle before it is believed.

export type SolutionVerification = {
  readonly valid: boolean;
  /** Words the client claimed that are genuinely in this puzzle. */
  readonly verifiedWords: readonly string[];
  /** Claimed words that do not exist in the puzzle at all. */
  readonly unknownWords: readonly string[];
  /** Real words the client has not found yet. */
  readonly missingWords: readonly string[];
  readonly completionPercent: number;
  readonly complete: boolean;
};

/**
 * Verifies a claimed set of found words against the stored solution.
 *
 * Trusting the client here would let anyone mark every journey complete by
 * posting a list of strings, which would corrupt progress, statistics and (in a
 * later phase) milestones.
 */
export function verifyClaimedSolution(input: {
  placements: readonly Placement[];
  claimedWords: readonly string[];
}): SolutionVerification {
  const actual = new Set(input.placements.map((placement) => placement.normalized));

  // De-duplicate first: repeating a word must not inflate completion.
  const claimed = [...new Set(input.claimedWords)];

  const verifiedWords = claimed.filter((word) => actual.has(word));
  const unknownWords = claimed.filter((word) => !actual.has(word));
  const verified = new Set(verifiedWords);
  const missingWords = [...actual].filter((word) => !verified.has(word));

  const total = actual.size;
  const completionPercent = total === 0 ? 100 : Math.round((verifiedWords.length / total) * 100);

  return {
    valid: unknownWords.length === 0,
    verifiedWords,
    unknownWords,
    missingWords,
    completionPercent,
    complete: total > 0 && verifiedWords.length === total,
  };
}

/**
 * Replays a sequence of selections against the grid.
 *
 * Stronger than `verifyClaimedSolution`: it checks that the reader's
 * SELECTIONS actually spell the words, not merely that the words exist. Use it
 * where the coordinates are available.
 */
export function replaySelections(input: {
  grid: Grid;
  placements: readonly Placement[];
  selections: readonly Selection[];
}): { readonly foundWords: string[]; readonly results: ValidationResult[] } {
  const targetWords = input.placements.map((placement) => placement.normalized);
  const foundWords: string[] = [];
  const results: ValidationResult[] = [];

  for (const selection of input.selections) {
    const result = validateSelection({
      grid: input.grid,
      selection,
      targetWords,
      foundWords,
      placements: input.placements,
    });
    results.push(result);
    if (result.kind === "match") foundWords.push(result.word);
  }

  return { foundWords, results };
}

/**
 * Confirms a stored puzzle is internally consistent — every placement really
 * spells its word in the persisted grid.
 *
 * Run when loading an instance generated by an older engine version, where a
 * behaviour change could have left the two out of step.
 */
export function verifyStoredPuzzle(input: {
  displayRows: readonly string[];
  normalizedRows: readonly string[];
  placements: readonly Placement[];
}): { readonly valid: boolean; readonly problems: readonly string[] } {
  const size = input.displayRows.length;
  const occupied = placementCells(input.placements);

  const grid: MutableGrid = {
    size,
    cells: input.displayRows.map((row, r) =>
      [...row].map((display, c) => ({
        display,
        normalized: input.normalizedRows[r]?.[c] ?? display,
        placementIds: occupied.has(`${r},${c}`) ? ["stored"] : [],
      })),
    ),
  };

  return validateGrid(grid, input.placements);
}

/** The full solution as cell paths, for rendering a reveal. */
export function solutionPaths(
  placements: readonly Placement[],
): { readonly word: string; readonly path: readonly { row: number; col: number }[] }[] {
  return placements.map((placement) => ({
    word: placement.normalized,
    path:
      placement.path.length > 0
        ? placement.path
        : pathOf({ start: placement.start, end: placement.end }),
  }));
}

/** Rebuilds a renderable grid from stored rows plus placements. */
export function gridFromStored(input: {
  displayRows: readonly string[];
  normalizedRows: readonly string[];
  placements: readonly Placement[];
}): Grid {
  return fromRows(input.displayRows, input.normalizedRows, placementCells(input.placements));
}
