import type { GameLocale } from "@/lib/games";
import type { WhoAmIQuestion } from "./types";

// Development content only — typed, local, deliberately not wired to Supabase.
// Same per-locale structure as Word Guess: pt/es slots exist and fall back to
// English until translated sets ship. Clues run vaguest → most revealing.

const EN_QUESTIONS: readonly WhoAmIQuestion[] = [
  {
    id: "wai-en-moses",
    locale: "en",
    clues: [
      "I was hidden in a basket as a baby.",
      "I grew up in a palace that was not my people's.",
      "I saw a bush that burned without burning up.",
      "I raised my staff and the sea opened before Israel.",
    ],
    answer: "MOSES",
    distractors: ["AARON", "JOSHUA", "ABRAHAM", "JACOB", "SAMUEL"],
    scriptureReference: "Exodus 3:1–12",
    explanation:
      "Moses was drawn from the Nile, called at the burning bush, and led Israel out of Egypt.",
    difficulty: "gentle",
    category: "people",
  },
  {
    id: "wai-en-noah",
    locale: "en",
    clues: [
      "People laughed while I worked for years.",
      "I built something enormous far from any sea.",
      "Animals came to me two by two.",
      "A dove brought me an olive leaf.",
    ],
    answer: "NOAH",
    distractors: ["ADAM", "ENOCH", "ABRAHAM", "LOT", "SETH"],
    scriptureReference: "Genesis 6–9",
    explanation: "Noah built the ark in faith and carried his family through the flood.",
    difficulty: "gentle",
    category: "people",
  },
  {
    id: "wai-en-david",
    locale: "en",
    clues: [
      "I was the youngest of eight brothers.",
      "I wrote songs while watching sheep.",
      "A king threw a spear at me while I played the harp.",
      "I felled a giant with a single stone.",
    ],
    answer: "DAVID",
    distractors: ["SAUL", "SOLOMON", "JONATHAN", "SAMSON", "GIDEON"],
    scriptureReference: "1 Samuel 17",
    explanation: "David, the shepherd of Bethlehem, became Israel's psalmist king.",
    difficulty: "gentle",
    category: "people",
  },
  {
    id: "wai-en-mary",
    locale: "en",
    clues: [
      "An angel called me highly favoured.",
      "I treasured certain things quietly in my heart.",
      "I laid my firstborn in a manger.",
      "I stood near the cross when most had fled.",
    ],
    answer: "MARY",
    distractors: ["ELIZABETH", "MARTHA", "RUTH", "HANNAH", "SARAH"],
    scriptureReference: "Luke 1:26–38",
    explanation:
      "Mary of Nazareth received the angel's word with faith and became the mother of Jesus.",
    difficulty: "gentle",
    category: "people",
  },
  {
    id: "wai-en-peter",
    locale: "en",
    clues: [
      "I worked with nets before I was called.",
      "I once walked on water — briefly.",
      "A rooster's crow broke my heart.",
      "Jesus asked me three times if I loved him.",
    ],
    answer: "PETER",
    acceptedAnswers: ["SIMON", "SIMON PETER", "CEPHAS"],
    distractors: ["ANDREW", "JAMES", "JOHN", "THOMAS", "PHILIP"],
    scriptureReference: "John 21:15–19",
    explanation:
      "Simon Peter, the fisherman, denied his Lord three times and was restored three times.",
    difficulty: "balanced",
    category: "people",
  },
  {
    id: "wai-en-jonah",
    locale: "en",
    clues: [
      "I bought a ticket in the opposite direction.",
      "A storm stopped because I went overboard.",
      "I prayed from a very unusual place for three days.",
      "A plant withered and I learned about mercy.",
    ],
    answer: "JONAH",
    distractors: ["ELIJAH", "ELISHA", "AMOS", "HOSEA", "MICAH"],
    scriptureReference: "Jonah 2",
    explanation:
      "Jonah ran from Nineveh, prayed from the fish's belly, and learned how wide God's compassion is.",
    difficulty: "balanced",
    category: "people",
  },
  {
    id: "wai-en-esther",
    locale: "en",
    clues: [
      "I had two names, one hidden with my past.",
      "I won a contest I never asked to enter.",
      "I fasted three days before breaking a law.",
      '"For such a time as this" was said of me.',
    ],
    answer: "ESTHER",
    acceptedAnswers: ["HADASSAH"],
    distractors: ["RUTH", "DEBORAH", "ABIGAIL", "MIRIAM", "NAOMI"],
    scriptureReference: "Esther 4:14",
    explanation: "Esther risked her life before the king and her people were saved.",
    difficulty: "balanced",
    category: "people",
  },
  {
    id: "wai-en-paul",
    locale: "en",
    clues: [
      "I guarded coats while a good man died.",
      "A light on a road changed everything.",
      "I made tents so no one would pay my way.",
      "I wrote letters from prison that still travel the world.",
    ],
    answer: "PAUL",
    acceptedAnswers: ["SAUL", "SAUL OF TARSUS"],
    distractors: ["BARNABAS", "SILAS", "TIMOTHY", "APOLLOS", "STEPHEN"],
    scriptureReference: "Acts 9:1–19",
    explanation:
      "Saul of Tarsus met the risen Christ on the Damascus road and became Paul, apostle to the nations.",
    difficulty: "balanced",
    category: "people",
  },
  {
    id: "wai-en-elijah",
    locale: "en",
    clues: [
      "Ravens brought me bread.",
      "I mocked prophets who shouted all day at nothing.",
      "Fire fell on a soaked altar when I prayed.",
      "I left in a chariot of fire.",
    ],
    answer: "ELIJAH",
    distractors: ["ELISHA", "ISAIAH", "JEREMIAH", "SAMUEL", "NATHAN"],
    scriptureReference: "1 Kings 18:30–39",
    explanation: "Elijah stood alone on Carmel, and the fire of the Lord answered.",
    difficulty: "challenging",
    category: "people",
  },
  {
    id: "wai-en-ruth",
    locale: "en",
    clues: [
      "I was not born among the people I chose.",
      '"Where you go, I will go", I said.',
      "I gleaned leftover grain to feed two widows.",
      "My great-grandson would be a famous king.",
    ],
    answer: "RUTH",
    distractors: ["NAOMI", "ORPAH", "ESTHER", "RACHEL", "TAMAR"],
    scriptureReference: "Ruth 1:16",
    explanation: "Ruth the Moabite chose Naomi's God and became great-grandmother of David.",
    difficulty: "challenging",
    category: "people",
  },
  {
    id: "wai-en-daniel",
    locale: "en",
    clues: [
      "I ate vegetables while others feasted.",
      "I read writing on a wall no one else could.",
      "I kept my window open toward Jerusalem, three times a day.",
      "Hungry lions kept me company for a night.",
    ],
    answer: "DANIEL",
    distractors: ["SHADRACH", "MESHACH", "ABEDNEGO", "EZEKIEL", "NEHEMIAH"],
    scriptureReference: "Daniel 6",
    explanation: "Daniel prayed as he always had, and God shut the lions' mouths.",
    difficulty: "challenging",
    category: "people",
  },
  {
    id: "wai-en-deborah",
    locale: "en",
    clues: [
      "I held court beneath a palm tree.",
      "I was a prophet and a judge in days when few listened.",
      "A general refused to go to battle without me.",
      "I sang of a victory sealed by a tent peg.",
    ],
    answer: "DEBORAH",
    distractors: ["JAEL", "MIRIAM", "HULDAH", "HANNAH", "ABIGAIL"],
    scriptureReference: "Judges 4–5",
    explanation: "Deborah judged Israel under her palm and led Barak to victory.",
    difficulty: "challenging",
    category: "people",
  },
  {
    id: "wai-en-john-baptist",
    locale: "en",
    clues: [
      "My food and clothes were nobody's envy.",
      "I preached where there were no pulpits.",
      "I said someone coming after me was greater.",
      "I baptized my own cousin in a river.",
    ],
    answer: "JOHN THE BAPTIST",
    acceptedAnswers: ["JOHN"],
    distractors: ["ELIJAH", "PETER", "ANDREW", "JAMES"],
    scriptureReference: "Matthew 3:1–17",
    explanation: "John prepared the way in the wilderness and baptized Jesus in the Jordan.",
    difficulty: "expert",
    category: "people",
  },
  {
    id: "wai-en-joseph",
    locale: "en",
    clues: [
      "My father gave me a coat my brothers hated.",
      "I was sold by my own family.",
      "I read dreams for a baker, a cupbearer and a king.",
      "I told my brothers: you meant evil, God meant good.",
    ],
    answer: "JOSEPH",
    distractors: ["BENJAMIN", "JUDAH", "REUBEN", "SIMEON", "LEVI"],
    scriptureReference: "Genesis 50:20",
    explanation: "Joseph forgave his brothers and kept a nation alive through famine.",
    difficulty: "balanced",
    category: "people",
  },
  {
    id: "wai-en-solomon",
    locale: "en",
    clues: [
      "I asked for something no one expected.",
      "I settled an argument between two mothers with a sword I never used.",
      "I built a house for the Name.",
      "I wrote that everything under the sun is vapour.",
    ],
    answer: "SOLOMON",
    distractors: ["DAVID", "REHOBOAM", "HEZEKIAH", "JOSIAH", "SAUL"],
    scriptureReference: "1 Kings 3:16–28",
    explanation: "Solomon asked for an understanding heart, and God gave him wisdom and more.",
    difficulty: "challenging",
    category: "people",
  },
  {
    id: "wai-en-samson",
    locale: "en",
    clues: [
      "I was set apart before I was born.",
      "I killed a lion and later found honey in it.",
      "I told my secret to the wrong person.",
      "My greatest strength came at my weakest hour.",
    ],
    answer: "SAMSON",
    distractors: ["GIDEON", "JEPHTHAH", "BARAK", "EHUD", "SAUL"],
    scriptureReference: "Judges 16:28–30",
    explanation: "Samson prayed one last time, and God answered.",
    difficulty: "challenging",
    category: "people",
  },
  {
    id: "wai-en-thomas",
    locale: "en",
    clues: [
      "I once said we should go and die with him.",
      "I was not there the first time he came.",
      "I wanted to see, not only hear.",
      "I called him my Lord and my God.",
    ],
    answer: "THOMAS",
    distractors: ["PHILIP", "ANDREW", "MATTHEW", "JAMES", "NATHANAEL"],
    scriptureReference: "John 20:24–29",
    explanation: "Thomas doubted, then made the fullest confession of them all.",
    difficulty: "expert",
    category: "people",
  },
  {
    id: "wai-en-martha",
    locale: "en",
    clues: [
      "I opened my home to him.",
      "I complained that I was working alone.",
      "My sister chose the better part.",
      "At my brother's tomb I said: I believe you are the Christ.",
    ],
    answer: "MARTHA",
    distractors: ["MARY", "JOANNA", "SALOME", "PRISCILLA", "TABITHA"],
    scriptureReference: "John 11:27",
    explanation: "Martha, so often remembered for her busyness, confessed the faith clearly.",
    difficulty: "expert",
    category: "people",
  },
  {
    id: "wai-en-zacchaeus",
    locale: "en",
    clues: [
      "My work made me rich and lonely.",
      "I could not see over the crowd.",
      "A tree solved my problem.",
      "He said he must stay at my house today.",
    ],
    answer: "ZACCHAEUS",
    distractors: ["MATTHEW", "NICODEMUS", "SIMON", "JAIRUS", "BARTIMAEUS"],
    scriptureReference: "Luke 19:1–10",
    explanation: "Zacchaeus came down quickly, and gave half of what he owned to the poor.",
    difficulty: "balanced",
    category: "people",
  },
  {
    id: "wai-en-joshua",
    locale: "en",
    clues: [
      "I was one of only two who came back with hope.",
      "I served another leader for forty years.",
      "My people marched in silence for six days.",
      "I said: as for me and my house, we will serve the Lord.",
    ],
    answer: "JOSHUA",
    distractors: ["CALEB", "AARON", "GIDEON", "SAMUEL", "ELEAZAR"],
    scriptureReference: "Joshua 24:15",
    explanation: "Joshua led Israel into the land and asked them to choose whom they would serve.",
    difficulty: "challenging",
    category: "people",
  },
  {
    id: "wai-en-sarah",
    locale: "en",
    clues: [
      "I waited longer than I thought possible.",
      "I laughed behind a tent door.",
      "I was ninety when I held my son.",
      "His name means laughter.",
    ],
    answer: "SARAH",
    distractors: ["HAGAR", "REBEKAH", "RACHEL", "LEAH", "MILCAH"],
    scriptureReference: "Genesis 21:1–7",
    explanation: "Sarah's laughter of disbelief became laughter of joy — Isaac.",
    difficulty: "gentle",
    category: "people",
  },
  {
    id: "wai-en-abraham",
    locale: "en",
    clues: [
      "I left home without knowing where I was going.",
      "I was promised descendants like the stars.",
      "I laughed, and so did my wife — then we named our son for it.",
      "I climbed a mountain with wood, fire, and a heavy heart.",
    ],
    answer: "ABRAHAM",
    acceptedAnswers: ["ABRAM"],
    distractors: ["ISAAC", "JACOB", "LOT", "NOAH"],
    scriptureReference: "Genesis 22:1–14",
    explanation: "Abraham trusted the God who provides, and on the mountain a ram was given.",
    difficulty: "expert",
    category: "people",
  },
];

const PT_QUESTIONS: readonly WhoAmIQuestion[] = [
  {
    id: "wai-pt-moises",
    locale: "pt",
    clues: [
      "Fui escondido num cesto quando bebê.",
      "Cresci num palácio que não era do meu povo.",
      "Vi uma sarça que ardia sem se consumir.",
      "Ergui meu cajado e o mar se abriu diante de Israel.",
    ],
    answer: "MOISÉS",
    distractors: ["ARÃO", "JOSUÉ", "ABRAÃO", "JACÓ", "SAMUEL"],
    scriptureReference: "Êxodo 3:1–12",
    explanation:
      "Moisés foi tirado do Nilo, chamado na sarça ardente, e conduziu Israel para fora do Egito.",
    difficulty: "gentle",
    category: "people",
  },
  {
    id: "wai-pt-noe",
    locale: "pt",
    clues: [
      "Riram de mim enquanto eu trabalhava por anos.",
      "Construí algo enorme longe de qualquer mar.",
      "Os animais vieram a mim de dois em dois.",
      "Uma pomba me trouxe uma folha de oliveira.",
    ],
    answer: "NOÉ",
    distractors: ["ADÃO", "ENOQUE", "ABRAÃO", "LÓ", "SETE"],
    scriptureReference: "Gênesis 6–9",
    explanation: "Noé construiu a arca pela fé e levou sua família em segurança pelo dilúvio.",
    difficulty: "gentle",
    category: "people",
  },
  {
    id: "wai-pt-davi",
    locale: "pt",
    clues: [
      "Eu era o caçula de oito irmãos.",
      "Compunha canções enquanto cuidava de ovelhas.",
      "Um rei atirou uma lança em mim enquanto eu tocava harpa.",
      "Derrubei um gigante com uma única pedra.",
    ],
    answer: "DAVI",
    distractors: ["SAUL", "SALOMÃO", "JÔNATAS", "SANSÃO", "GIDEÃO"],
    scriptureReference: "1 Samuel 17",
    explanation: "Davi, o pastor de Belém, tornou-se o rei salmista de Israel.",
    difficulty: "gentle",
    category: "people",
  },
  {
    id: "wai-pt-maria",
    locale: "pt",
    clues: [
      "Um anjo me chamou de muito favorecida.",
      "Guardei certas coisas em silêncio no coração.",
      "Deitei meu primogênito numa manjedoura.",
      "Fiquei perto da cruz quando quase todos fugiram.",
    ],
    answer: "MARIA",
    distractors: ["ISABEL", "MARTA", "RUTE", "ANA", "SARA"],
    scriptureReference: "Lucas 1:26–38",
    explanation: "Maria de Nazaré recebeu com fé a palavra do anjo e tornou-se a mãe de Jesus.",
    difficulty: "gentle",
    category: "people",
  },
  {
    id: "wai-pt-pedro",
    locale: "pt",
    clues: [
      "Trabalhava com redes antes de ser chamado.",
      "Uma vez andei sobre as águas — por pouco tempo.",
      "O canto de um galo partiu meu coração.",
      "Jesus me perguntou três vezes se eu o amava.",
    ],
    answer: "PEDRO",
    acceptedAnswers: ["SIMÃO", "SIMÃO PEDRO", "CEFAS"],
    distractors: ["ANDRÉ", "TIAGO", "JOÃO", "TOMÉ", "FILIPE"],
    scriptureReference: "João 21:15–19",
    explanation:
      "Simão Pedro, o pescador, negou seu Senhor três vezes e foi restaurado três vezes.",
    difficulty: "balanced",
    category: "people",
  },
  {
    id: "wai-pt-jonas",
    locale: "pt",
    clues: [
      "Comprei passagem na direção contrária.",
      "Uma tempestade parou porque me lançaram ao mar.",
      "Orei de um lugar muito incomum por três dias.",
      "Uma planta secou e aprendi sobre misericórdia.",
    ],
    answer: "JONAS",
    distractors: ["ELIAS", "ELISEU", "AMÓS", "OSEIAS", "MIQUEIAS"],
    scriptureReference: "Jonas 2",
    explanation:
      "Jonas fugiu de Nínive, orou do ventre do peixe e aprendeu como é vasta a compaixão de Deus.",
    difficulty: "balanced",
    category: "people",
  },
  {
    id: "wai-pt-ester",
    locale: "pt",
    clues: [
      "Tive dois nomes, um escondido com meu passado.",
      "Venci um concurso em que nunca pedi para entrar.",
      "Jejuei três dias antes de quebrar uma lei.",
      '"Para um tempo como este" foi dito de mim.',
    ],
    answer: "ESTER",
    acceptedAnswers: ["HADASSA"],
    distractors: ["RUTE", "DÉBORA", "ABIGAIL", "MIRIÃ", "NOEMI"],
    scriptureReference: "Ester 4:14",
    explanation: "Ester arriscou a vida diante do rei e seu povo foi salvo.",
    difficulty: "balanced",
    category: "people",
  },
  {
    id: "wai-pt-paulo",
    locale: "pt",
    clues: [
      "Guardei capas enquanto um homem bom morria.",
      "Uma luz numa estrada mudou tudo.",
      "Fazia tendas para não pesar a ninguém.",
      "Escrevi cartas da prisão que ainda correm o mundo.",
    ],
    answer: "PAULO",
    acceptedAnswers: ["SAULO", "SAULO DE TARSO"],
    distractors: ["BARNABÉ", "SILAS", "TIMÓTEO", "APOLO", "ESTÊVÃO"],
    scriptureReference: "Atos 9:1–19",
    explanation:
      "Saulo de Tarso encontrou o Cristo ressuscitado no caminho de Damasco e tornou-se Paulo, apóstolo das nações.",
    difficulty: "balanced",
    category: "people",
  },
  {
    id: "wai-pt-elias",
    locale: "pt",
    clues: [
      "Corvos me traziam pão.",
      "Zombei de profetas que gritavam o dia todo para o nada.",
      "Fogo caiu sobre um altar encharcado quando orei.",
      "Parti num carro de fogo.",
    ],
    answer: "ELIAS",
    distractors: ["ELISEU", "ISAÍAS", "JEREMIAS", "SAMUEL", "NATÃ"],
    scriptureReference: "1 Reis 18:30–39",
    explanation: "Elias ficou sozinho no Carmelo, e o fogo do Senhor respondeu.",
    difficulty: "challenging",
    category: "people",
  },
  {
    id: "wai-pt-rute",
    locale: "pt",
    clues: [
      "Não nasci entre o povo que escolhi.",
      '"Aonde quer que fores, irei", eu disse.',
      "Colhia espigas deixadas para sustentar duas viúvas.",
      "Meu bisneto seria um rei famoso.",
    ],
    answer: "RUTE",
    distractors: ["NOEMI", "ORFA", "ESTER", "RAQUEL", "TAMAR"],
    scriptureReference: "Rute 1:16",
    explanation: "Rute, a moabita, escolheu o Deus de Noemi e tornou-se bisavó de Davi.",
    difficulty: "challenging",
    category: "people",
  },
  {
    id: "wai-pt-daniel",
    locale: "pt",
    clues: [
      "Comia legumes enquanto outros banqueteavam.",
      "Li uma escrita na parede que ninguém mais conseguia.",
      "Mantinha minha janela aberta para Jerusalém, três vezes ao dia.",
      "Leões famintos me fizeram companhia por uma noite.",
    ],
    answer: "DANIEL",
    distractors: ["SADRAQUE", "MESAQUE", "ABEDNEGO", "EZEQUIEL", "NEEMIAS"],
    scriptureReference: "Daniel 6",
    explanation: "Daniel orou como sempre orava, e Deus fechou a boca dos leões.",
    difficulty: "challenging",
    category: "people",
  },
  {
    id: "wai-pt-debora",
    locale: "pt",
    clues: [
      "Julgava debaixo de uma palmeira.",
      "Fui profetisa e juíza em dias em que poucos ouviam.",
      "Um general recusou ir à batalha sem mim.",
      "Cantei uma vitória selada por uma estaca de tenda.",
    ],
    answer: "DÉBORA",
    distractors: ["JAEL", "MIRIÃ", "HULDA", "ANA", "ABIGAIL"],
    scriptureReference: "Juízes 4–5",
    explanation: "Débora julgou Israel sob sua palmeira e levou Baraque à vitória.",
    difficulty: "challenging",
    category: "people",
  },
  {
    id: "wai-pt-joao-batista",
    locale: "pt",
    clues: [
      "Minha comida e minhas roupas não davam inveja a ninguém.",
      "Preguei onde não havia púlpitos.",
      "Disse que alguém vindo depois de mim era maior.",
      "Batizei meu próprio primo num rio.",
    ],
    answer: "JOÃO BATISTA",
    acceptedAnswers: ["JOÃO"],
    distractors: ["ELIAS", "PEDRO", "ANDRÉ", "TIAGO"],
    scriptureReference: "Mateus 3:1–17",
    explanation: "João preparou o caminho no deserto e batizou Jesus no Jordão.",
    difficulty: "expert",
    category: "people",
  },
  {
    id: "wai-pt-jose",
    locale: "pt",
    clues: [
      "Meu pai me deu uma túnica que meus irmãos odiaram.",
      "Fui vendido pela minha própria família.",
      "Interpretei sonhos de um padeiro, um copeiro e um rei.",
      "Disse aos meus irmãos: vocês pensaram o mal, Deus pensou o bem.",
    ],
    answer: "JOSÉ",
    distractors: ["BENJAMIM", "JUDÁ", "RÚBEN", "SIMEÃO", "LEVI"],
    scriptureReference: "Gênesis 50:20",
    explanation: "José perdoou os irmãos e manteve uma nação viva durante a fome.",
    difficulty: "balanced",
    category: "people",
  },
  {
    id: "wai-pt-salomao",
    locale: "pt",
    clues: [
      "Pedi algo que ninguém esperava.",
      "Resolvi a disputa de duas mães com uma espada que nunca usei.",
      "Construí uma casa para o Nome.",
      "Escrevi que tudo debaixo do sol é vaidade.",
    ],
    answer: "SALOMÃO",
    distractors: ["DAVI", "ROBOÃO", "EZEQUIAS", "JOSIAS", "SAUL"],
    scriptureReference: "1 Reis 3:16–28",
    explanation: "Salomão pediu um coração que soubesse entender, e Deus lhe deu sabedoria e mais.",
    difficulty: "challenging",
    category: "people",
  },
  {
    id: "wai-pt-sansao",
    locale: "pt",
    clues: [
      "Fui separado antes de nascer.",
      "Matei um leão e depois achei mel nele.",
      "Contei meu segredo à pessoa errada.",
      "Minha maior força veio na minha hora mais fraca.",
    ],
    answer: "SANSÃO",
    distractors: ["GIDEÃO", "JEFTÉ", "BARAQUE", "EÚDE", "SAUL"],
    scriptureReference: "Juízes 16:28–30",
    explanation: "Sansão orou uma última vez, e Deus respondeu.",
    difficulty: "challenging",
    category: "people",
  },
  {
    id: "wai-pt-tome",
    locale: "pt",
    clues: [
      "Certa vez disse que devíamos ir e morrer com ele.",
      "Não estava lá na primeira vez em que ele veio.",
      "Eu queria ver, não apenas ouvir.",
      "Chamei-o de Senhor meu e Deus meu.",
    ],
    answer: "TOMÉ",
    distractors: ["FILIPE", "ANDRÉ", "MATEUS", "TIAGO", "NATANAEL"],
    scriptureReference: "João 20:24–29",
    explanation: "Tomé duvidou e depois fez a confissão mais plena de todos.",
    difficulty: "expert",
    category: "people",
  },
  {
    id: "wai-pt-marta",
    locale: "pt",
    clues: [
      "Abri minha casa para ele.",
      "Reclamei que estava trabalhando sozinha.",
      "Minha irmã escolheu a melhor parte.",
      "Diante do túmulo do meu irmão eu disse: creio que tu és o Cristo.",
    ],
    answer: "MARTA",
    distractors: ["MARIA", "JOANA", "SALOMÉ", "PRISCILA", "TABITA"],
    scriptureReference: "João 11:27",
    explanation: "Marta, lembrada por sua correria, confessou a fé com clareza.",
    difficulty: "expert",
    category: "people",
  },
  {
    id: "wai-pt-zaqueu",
    locale: "pt",
    clues: [
      "Meu trabalho me deixou rico e sozinho.",
      "Não conseguia enxergar por cima da multidão.",
      "Uma árvore resolveu meu problema.",
      "Ele disse que precisava ficar na minha casa naquele dia.",
    ],
    answer: "ZAQUEU",
    distractors: ["MATEUS", "NICODEMOS", "SIMÃO", "JAIRO", "BARTIMEU"],
    scriptureReference: "Lucas 19:1–10",
    explanation: "Zaqueu desceu depressa e deu metade do que tinha aos pobres.",
    difficulty: "balanced",
    category: "people",
  },
  {
    id: "wai-pt-josue",
    locale: "pt",
    clues: [
      "Fui um dos dois únicos que voltaram com esperança.",
      "Servi outro líder por quarenta anos.",
      "Meu povo marchou em silêncio por seis dias.",
      "Eu disse: eu e a minha casa serviremos ao Senhor.",
    ],
    answer: "JOSUÉ",
    distractors: ["CALEBE", "ARÃO", "GIDEÃO", "SAMUEL", "ELEAZAR"],
    scriptureReference: "Josué 24:15",
    explanation: "Josué levou Israel à terra e pediu que escolhessem a quem serviriam.",
    difficulty: "challenging",
    category: "people",
  },
  {
    id: "wai-pt-sara",
    locale: "pt",
    clues: [
      "Esperei mais do que achei possível.",
      "Ri atrás da porta da tenda.",
      "Tinha noventa anos quando segurei meu filho.",
      "O nome dele significa riso.",
    ],
    answer: "SARA",
    distractors: ["AGAR", "REBECA", "RAQUEL", "LIA", "MILCA"],
    scriptureReference: "Gênesis 21:1–7",
    explanation: "O riso de incredulidade de Sara virou riso de alegria — Isaque.",
    difficulty: "gentle",
    category: "people",
  },
  {
    id: "wai-pt-abraao",
    locale: "pt",
    clues: [
      "Saí de casa sem saber para onde ia.",
      "Recebi a promessa de descendentes como as estrelas.",
      "Eu ri, minha esposa também — e demos ao filho um nome por isso.",
      "Subi um monte com lenha, fogo e o coração pesado.",
    ],
    answer: "ABRAÃO",
    acceptedAnswers: ["ABRÃO"],
    distractors: ["ISAQUE", "JACÓ", "LÓ", "NOÉ"],
    scriptureReference: "Gênesis 22:1–14",
    explanation: "Abraão confiou no Deus que provê, e no monte um cordeiro foi dado.",
    difficulty: "expert",
    category: "people",
  },
];

const ES_QUESTIONS: readonly WhoAmIQuestion[] = [
  {
    id: "wai-es-moises",
    locale: "es",
    clues: [
      "Fui escondido en una cesta cuando era bebé.",
      "Crecí en un palacio que no era de mi pueblo.",
      "Vi una zarza que ardía sin consumirse.",
      "Levanté mi vara y el mar se abrió ante Israel.",
    ],
    answer: "MOISÉS",
    distractors: ["AARÓN", "JOSUÉ", "ABRAHAM", "JACOB", "SAMUEL"],
    scriptureReference: "Éxodo 3:1–12",
    explanation:
      "Moisés fue sacado del Nilo, llamado en la zarza ardiente, y sacó a Israel de Egipto.",
    difficulty: "gentle",
    category: "people",
  },
  {
    id: "wai-es-noe",
    locale: "es",
    clues: [
      "Se rieron de mí mientras trabajaba durante años.",
      "Construí algo enorme lejos de cualquier mar.",
      "Los animales vinieron a mí de dos en dos.",
      "Una paloma me trajo una hoja de olivo.",
    ],
    answer: "NOÉ",
    distractors: ["ADÁN", "ENOC", "ABRAHAM", "LOT", "SET"],
    scriptureReference: "Génesis 6–9",
    explanation: "Noé construyó el arca por fe y llevó a su familia a salvo por el diluvio.",
    difficulty: "gentle",
    category: "people",
  },
  {
    id: "wai-es-david",
    locale: "es",
    clues: [
      "Era el menor de ocho hermanos.",
      "Componía canciones mientras cuidaba ovejas.",
      "Un rey me arrojó una lanza mientras tocaba el arpa.",
      "Derribé a un gigante con una sola piedra.",
    ],
    answer: "DAVID",
    distractors: ["SAÚL", "SALOMÓN", "JONATÁN", "SANSÓN", "GEDEÓN"],
    scriptureReference: "1 Samuel 17",
    explanation: "David, el pastor de Belén, llegó a ser el rey salmista de Israel.",
    difficulty: "gentle",
    category: "people",
  },
  {
    id: "wai-es-maria",
    locale: "es",
    clues: [
      "Un ángel me llamó muy favorecida.",
      "Guardaba ciertas cosas en silencio en mi corazón.",
      "Acosté a mi primogénito en un pesebre.",
      "Estuve junto a la cruz cuando casi todos huyeron.",
    ],
    answer: "MARÍA",
    distractors: ["ISABEL", "MARTA", "RUT", "ANA", "SARA"],
    scriptureReference: "Lucas 1:26–38",
    explanation: "María de Nazaret recibió con fe la palabra del ángel y fue la madre de Jesús.",
    difficulty: "gentle",
    category: "people",
  },
  {
    id: "wai-es-pedro",
    locale: "es",
    clues: [
      "Trabajaba con redes antes de ser llamado.",
      "Una vez caminé sobre el agua — por poco tiempo.",
      "El canto de un gallo me rompió el corazón.",
      "Jesús me preguntó tres veces si lo amaba.",
    ],
    answer: "PEDRO",
    acceptedAnswers: ["SIMÓN", "SIMÓN PEDRO", "CEFAS"],
    distractors: ["ANDRÉS", "SANTIAGO", "JUAN", "TOMÁS", "FELIPE"],
    scriptureReference: "Juan 21:15–19",
    explanation:
      "Simón Pedro, el pescador, negó a su Señor tres veces y fue restaurado tres veces.",
    difficulty: "balanced",
    category: "people",
  },
  {
    id: "wai-es-jonas",
    locale: "es",
    clues: [
      "Compré pasaje en la dirección contraria.",
      "Una tormenta se detuvo porque me echaron al mar.",
      "Oré desde un lugar muy inusual durante tres días.",
      "Una planta se secó y aprendí sobre la misericordia.",
    ],
    answer: "JONÁS",
    distractors: ["ELÍAS", "ELISEO", "AMÓS", "OSEAS", "MIQUEAS"],
    scriptureReference: "Jonás 2",
    explanation:
      "Jonás huyó de Nínive, oró desde el vientre del pez y aprendió cuán ancha es la compasión de Dios.",
    difficulty: "balanced",
    category: "people",
  },
  {
    id: "wai-es-ester",
    locale: "es",
    clues: [
      "Tuve dos nombres, uno escondido con mi pasado.",
      "Gané un concurso al que nunca pedí entrar.",
      "Ayuné tres días antes de quebrantar una ley.",
      '"Para esta hora" se dijo de mí.',
    ],
    answer: "ESTER",
    acceptedAnswers: ["HADASA"],
    distractors: ["RUT", "DÉBORA", "ABIGAIL", "MIRIAM", "NOEMÍ"],
    scriptureReference: "Ester 4:14",
    explanation: "Ester arriesgó su vida ante el rey y su pueblo fue salvado.",
    difficulty: "balanced",
    category: "people",
  },
  {
    id: "wai-es-pablo",
    locale: "es",
    clues: [
      "Guardé mantos mientras moría un hombre bueno.",
      "Una luz en un camino lo cambió todo.",
      "Hacía tiendas para no ser carga de nadie.",
      "Escribí cartas desde la cárcel que aún recorren el mundo.",
    ],
    answer: "PABLO",
    acceptedAnswers: ["SAULO", "SAULO DE TARSO"],
    distractors: ["BERNABÉ", "SILAS", "TIMOTEO", "APOLOS", "ESTEBAN"],
    scriptureReference: "Hechos 9:1–19",
    explanation:
      "Saulo de Tarso encontró al Cristo resucitado camino a Damasco y llegó a ser Pablo, apóstol de las naciones.",
    difficulty: "balanced",
    category: "people",
  },
  {
    id: "wai-es-elias",
    locale: "es",
    clues: [
      "Los cuervos me traían pan.",
      "Me burlé de profetas que gritaban todo el día a la nada.",
      "Cayó fuego sobre un altar empapado cuando oré.",
      "Partí en un carro de fuego.",
    ],
    answer: "ELÍAS",
    distractors: ["ELISEO", "ISAÍAS", "JEREMÍAS", "SAMUEL", "NATÁN"],
    scriptureReference: "1 Reyes 18:30–39",
    explanation: "Elías estuvo solo en el Carmelo, y el fuego del Señor respondió.",
    difficulty: "challenging",
    category: "people",
  },
  {
    id: "wai-es-rut",
    locale: "es",
    clues: [
      "No nací entre el pueblo que elegí.",
      '"A dondequiera que vayas, iré", dije.',
      "Espigaba lo que quedaba para sostener a dos viudas.",
      "Mi bisnieto sería un rey famoso.",
    ],
    answer: "RUT",
    distractors: ["NOEMÍ", "ORFA", "ESTER", "RAQUEL", "TAMAR"],
    scriptureReference: "Rut 1:16",
    explanation: "Rut la moabita eligió al Dios de Noemí y fue bisabuela de David.",
    difficulty: "challenging",
    category: "people",
  },
  {
    id: "wai-es-daniel",
    locale: "es",
    clues: [
      "Comía legumbres mientras otros banqueteaban.",
      "Leí una escritura en la pared que nadie más podía.",
      "Mantenía mi ventana abierta hacia Jerusalén, tres veces al día.",
      "Leones hambrientos me acompañaron una noche.",
    ],
    answer: "DANIEL",
    distractors: ["SADRAC", "MESAC", "ABEDNEGO", "EZEQUIEL", "NEHEMÍAS"],
    scriptureReference: "Daniel 6",
    explanation: "Daniel oró como siempre, y Dios cerró la boca de los leones.",
    difficulty: "challenging",
    category: "people",
  },
  {
    id: "wai-es-debora",
    locale: "es",
    clues: [
      "Juzgaba bajo una palmera.",
      "Fui profetisa y jueza en días en que pocos escuchaban.",
      "Un general se negó a ir a la batalla sin mí.",
      "Canté una victoria sellada con una estaca de tienda.",
    ],
    answer: "DÉBORA",
    distractors: ["JAEL", "MIRIAM", "HULDA", "ANA", "ABIGAIL"],
    scriptureReference: "Jueces 4–5",
    explanation: "Débora juzgó a Israel bajo su palmera y llevó a Barac a la victoria.",
    difficulty: "challenging",
    category: "people",
  },
  {
    id: "wai-es-juan-bautista",
    locale: "es",
    clues: [
      "Mi comida y mi ropa no daban envidia a nadie.",
      "Prediqué donde no había púlpitos.",
      "Dije que alguien que venía después de mí era mayor.",
      "Bauticé a mi propio primo en un río.",
    ],
    answer: "JUAN EL BAUTISTA",
    acceptedAnswers: ["JUAN", "JUAN BAUTISTA"],
    distractors: ["ELÍAS", "PEDRO", "ANDRÉS", "SANTIAGO"],
    scriptureReference: "Mateo 3:1–17",
    explanation: "Juan preparó el camino en el desierto y bautizó a Jesús en el Jordán.",
    difficulty: "expert",
    category: "people",
  },
  {
    id: "wai-es-jose",
    locale: "es",
    clues: [
      "Mi padre me dio una túnica que mis hermanos odiaron.",
      "Fui vendido por mi propia familia.",
      "Interpreté sueños de un panadero, un copero y un rey.",
      "Les dije a mis hermanos: ustedes pensaron mal, Dios lo pensó para bien.",
    ],
    answer: "JOSÉ",
    distractors: ["BENJAMÍN", "JUDÁ", "RUBÉN", "SIMEÓN", "LEVÍ"],
    scriptureReference: "Génesis 50:20",
    explanation: "José perdonó a sus hermanos y mantuvo viva a una nación durante el hambre.",
    difficulty: "balanced",
    category: "people",
  },
  {
    id: "wai-es-salomon",
    locale: "es",
    clues: [
      "Pedí algo que nadie esperaba.",
      "Resolví la disputa de dos madres con una espada que nunca usé.",
      "Construí una casa para el Nombre.",
      "Escribí que todo debajo del sol es vanidad.",
    ],
    answer: "SALOMÓN",
    distractors: ["DAVID", "ROBOAM", "EZEQUÍAS", "JOSÍAS", "SAÚL"],
    scriptureReference: "1 Reyes 3:16–28",
    explanation: "Salomón pidió un corazón entendido, y Dios le dio sabiduría y más.",
    difficulty: "challenging",
    category: "people",
  },
  {
    id: "wai-es-sanson",
    locale: "es",
    clues: [
      "Fui apartado antes de nacer.",
      "Maté un león y luego encontré miel en él.",
      "Conté mi secreto a la persona equivocada.",
      "Mi mayor fuerza llegó en mi hora más débil.",
    ],
    answer: "SANSÓN",
    distractors: ["GEDEÓN", "JEFTÉ", "BARAC", "AOD", "SAÚL"],
    scriptureReference: "Jueces 16:28–30",
    explanation: "Sansón oró una última vez, y Dios respondió.",
    difficulty: "challenging",
    category: "people",
  },
  {
    id: "wai-es-tomas",
    locale: "es",
    clues: [
      "Una vez dije que fuéramos a morir con él.",
      "No estuve la primera vez que él vino.",
      "Yo quería ver, no solo oír.",
      "Lo llamé Señor mío y Dios mío.",
    ],
    answer: "TOMÁS",
    distractors: ["FELIPE", "ANDRÉS", "MATEO", "SANTIAGO", "NATANAEL"],
    scriptureReference: "Juan 20:24–29",
    explanation: "Tomás dudó y después hizo la confesión más plena de todas.",
    difficulty: "expert",
    category: "people",
  },
  {
    id: "wai-es-marta",
    locale: "es",
    clues: [
      "Abrí mi casa para él.",
      "Me quejé de que trabajaba sola.",
      "Mi hermana escogió la mejor parte.",
      "Ante la tumba de mi hermano dije: creo que tú eres el Cristo.",
    ],
    answer: "MARTA",
    distractors: ["MARÍA", "JUANA", "SALOMÉ", "PRISCILA", "TABITA"],
    scriptureReference: "Juan 11:27",
    explanation: "Marta, recordada por su afán, confesó la fe con claridad.",
    difficulty: "expert",
    category: "people",
  },
  {
    id: "wai-es-zaqueo",
    locale: "es",
    clues: [
      "Mi trabajo me hizo rico y solitario.",
      "No podía ver por encima de la multitud.",
      "Un árbol resolvió mi problema.",
      "Él dijo que debía quedarse en mi casa ese día.",
    ],
    answer: "ZAQUEO",
    distractors: ["MATEO", "NICODEMO", "SIMÓN", "JAIRO", "BARTIMEO"],
    scriptureReference: "Lucas 19:1–10",
    explanation: "Zaqueo bajó de prisa y dio la mitad de lo que tenía a los pobres.",
    difficulty: "balanced",
    category: "people",
  },
  {
    id: "wai-es-josue",
    locale: "es",
    clues: [
      "Fui uno de los dos únicos que volvieron con esperanza.",
      "Serví a otro líder durante cuarenta años.",
      "Mi pueblo marchó en silencio seis días.",
      "Dije: yo y mi casa serviremos al Señor.",
    ],
    answer: "JOSUÉ",
    distractors: ["CALEB", "AARÓN", "GEDEÓN", "SAMUEL", "ELEAZAR"],
    scriptureReference: "Josué 24:15",
    explanation: "Josué llevó a Israel a la tierra y les pidió elegir a quién servirían.",
    difficulty: "challenging",
    category: "people",
  },
  {
    id: "wai-es-sara",
    locale: "es",
    clues: [
      "Esperé más de lo que creí posible.",
      "Me reí detrás de la puerta de la tienda.",
      "Tenía noventa años cuando sostuve a mi hijo.",
      "Su nombre significa risa.",
    ],
    answer: "SARA",
    distractors: ["AGAR", "REBECA", "RAQUEL", "LEA", "MILCA"],
    scriptureReference: "Génesis 21:1–7",
    explanation: "La risa de incredulidad de Sara se volvió risa de alegría — Isaac.",
    difficulty: "gentle",
    category: "people",
  },
  {
    id: "wai-es-abraham",
    locale: "es",
    clues: [
      "Salí de casa sin saber a dónde iba.",
      "Recibí la promesa de descendientes como las estrellas.",
      "Me reí, mi esposa también — y al hijo le dimos un nombre por eso.",
      "Subí un monte con leña, fuego y el corazón pesado.",
    ],
    answer: "ABRAHAM",
    acceptedAnswers: ["ABRAM"],
    distractors: ["ISAAC", "JACOB", "LOT", "NOÉ"],
    scriptureReference: "Génesis 22:1–14",
    explanation: "Abraham confió en el Dios que provee, y en el monte fue dado un cordero.",
    difficulty: "expert",
    category: "people",
  },
];

const QUESTIONS_BY_LOCALE: Record<GameLocale, readonly WhoAmIQuestion[]> = {
  en: EN_QUESTIONS,
  pt: PT_QUESTIONS,
  es: ES_QUESTIONS,
};

export function whoAmIQuestionsForLocale(locale: GameLocale): readonly WhoAmIQuestion[] {
  const set = QUESTIONS_BY_LOCALE[locale];
  return set.length > 0 ? set : QUESTIONS_BY_LOCALE.en;
}
