/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TogetherRouteImport } from './routes/together'
import { Route as TodayRouteImport } from './routes/today'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as MyJourneyRouteImport } from './routes/my-journey'
import { Route as ForgotRouteImport } from './routes/forgot'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as CollectionsRouteImport } from './routes/collections'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NotificationsPreferencesRouteImport } from './routes/notifications.preferences'

const TogetherRoute = TogetherRouteImport.update({
  id: '/together',
  path: '/together',
  getParentRoute: () => rootRouteImport,
} as any)
const TodayRoute = TodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MyJourneyRoute = MyJourneyRouteImport.update({
  id: '/my-journey',
  path: '/my-journey',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotRoute = ForgotRouteImport.update({
  id: '/forgot',
  path: '/forgot',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsRoute = CollectionsRouteImport.update({
  id: '/collections',
  path: '/collections',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsPreferencesRoute =
  NotificationsPreferencesRouteImport.update({
    id: '/preferences',
    path: '/preferences',
    getParentRoute: () => NotificationsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/collections': typeof CollectionsRoute
  '/favorites': typeof FavoritesRoute
  '/features': typeof FeaturesRoute
  '/forgot': typeof ForgotRoute
  '/my-journey': typeof MyJourneyRoute
  '/notifications': typeof NotificationsRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/profile': typeof ProfileRoute
  '/progress': typeof ProgressRoute
  '/settings': typeof SettingsRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/today': typeof TodayRoute
  '/together': typeof TogetherRoute
  '/notifications/preferences': typeof NotificationsPreferencesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/collections': typeof CollectionsRoute
  '/favorites': typeof FavoritesRoute
  '/features': typeof FeaturesRoute
  '/forgot': typeof ForgotRoute
  '/my-journey': typeof MyJourneyRoute
  '/notifications': typeof NotificationsRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/profile': typeof ProfileRoute
  '/progress': typeof ProgressRoute
  '/settings': typeof SettingsRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/today': typeof TodayRoute
  '/together': typeof TogetherRoute
  '/notifications/preferences': typeof NotificationsPreferencesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/collections': typeof CollectionsRoute
  '/favorites': typeof FavoritesRoute
  '/features': typeof FeaturesRoute
  '/forgot': typeof ForgotRoute
  '/my-journey': typeof MyJourneyRoute
  '/notifications': typeof NotificationsRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/profile': typeof ProfileRoute
  '/progress': typeof ProgressRoute
  '/settings': typeof SettingsRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/today': typeof TodayRoute
  '/together': typeof TogetherRoute
  '/notifications/preferences': typeof NotificationsPreferencesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/collections'
    | '/favorites'
    | '/features'
    | '/forgot'
    | '/my-journey'
    | '/notifications'
    | '/onboarding'
    | '/pricing'
    | '/profile'
    | '/progress'
    | '/settings'
    | '/signin'
    | '/signup'
    | '/sitemap.xml'
    | '/today'
    | '/together'
    | '/notifications/preferences'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/collections'
    | '/favorites'
    | '/features'
    | '/forgot'
    | '/my-journey'
    | '/notifications'
    | '/onboarding'
    | '/pricing'
    | '/profile'
    | '/progress'
    | '/settings'
    | '/signin'
    | '/signup'
    | '/sitemap.xml'
    | '/today'
    | '/together'
    | '/notifications/preferences'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/collections'
    | '/favorites'
    | '/features'
    | '/forgot'
    | '/my-journey'
    | '/notifications'
    | '/onboarding'
    | '/pricing'
    | '/profile'
    | '/progress'
    | '/settings'
    | '/signin'
    | '/signup'
    | '/sitemap.xml'
    | '/today'
    | '/together'
    | '/notifications/preferences'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CollectionsRoute: typeof CollectionsRoute
  FavoritesRoute: typeof FavoritesRoute
  FeaturesRoute: typeof FeaturesRoute
  ForgotRoute: typeof ForgotRoute
  MyJourneyRoute: typeof MyJourneyRoute
  NotificationsRoute: typeof NotificationsRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
  PricingRoute: typeof PricingRoute
  ProfileRoute: typeof ProfileRoute
  ProgressRoute: typeof ProgressRoute
  SettingsRoute: typeof SettingsRoute
  SigninRoute: typeof SigninRoute
  SignupRoute: typeof SignupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TodayRoute: typeof TodayRoute
  TogetherRoute: typeof TogetherRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/together': {
      id: '/together'
      path: '/together'
      fullPath: '/together'
      preLoaderRoute: typeof TogetherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/today': {
      id: '/today'
      path: '/today'
      fullPath: '/today'
      preLoaderRoute: typeof TodayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-journey': {
      id: '/my-journey'
      path: '/my-journey'
      fullPath: '/my-journey'
      preLoaderRoute: typeof MyJourneyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot': {
      id: '/forgot'
      path: '/forgot'
      fullPath: '/forgot'
      preLoaderRoute: typeof ForgotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections': {
      id: '/collections'
      path: '/collections'
      fullPath: '/collections'
      preLoaderRoute: typeof CollectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications/preferences': {
      id: '/notifications/preferences'
      path: '/preferences'
      fullPath: '/notifications/preferences'
      preLoaderRoute: typeof NotificationsPreferencesRouteImport
      parentRoute: typeof NotificationsRoute
    }
  }
}

interface NotificationsRouteChildren {
  NotificationsPreferencesRoute: typeof NotificationsPreferencesRoute
}

const NotificationsRouteChildren: NotificationsRouteChildren = {
  NotificationsPreferencesRoute: NotificationsPreferencesRoute,
}

const NotificationsRouteWithChildren = NotificationsRoute._addFileChildren(
  NotificationsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CollectionsRoute: CollectionsRoute,
  FavoritesRoute: FavoritesRoute,
  FeaturesRoute: FeaturesRoute,
  ForgotRoute: ForgotRoute,
  MyJourneyRoute: MyJourneyRoute,
  NotificationsRoute: NotificationsRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
  PricingRoute: PricingRoute,
  ProfileRoute: ProfileRoute,
  ProgressRoute: ProgressRoute,
  SettingsRoute: SettingsRoute,
  SigninRoute: SigninRoute,
  SignupRoute: SignupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TodayRoute: TodayRoute,
  TogetherRoute: TogetherRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
