with src(slug, tier, pos, en, pt, es) as (values
('psalm-23-the-shepherd','balanced',6,'PASTURES','PASTAGENS','PASTOS'),
('psalm-23-the-shepherd','balanced',7,'VALLEY','VALE','VALLE'),
('psalm-23-the-shepherd','balanced',8,'COMFORT','CONFORTO','CONSUELO'),
('psalm-23-the-shepherd','challenging',9,'GOODNESS','BONDADE','BONDAD'),
('psalm-23-the-shepherd','challenging',10,'MERCY','MISERICÓRDIA','MISERICORDIA'),
('psalm-23-the-shepherd','challenging',11,'TABLE','MESA','MESA'),
('psalm-23-the-shepherd','expert',12,'ANOINTS','UNGES','UNGES'),
('psalm-23-the-shepherd','expert',13,'DWELL','HABITAR','HABITAR'),
('psalm-23-the-shepherd','expert',14,'STAFF','CAJADO','CAYADO'),
('psalm-23-the-shepherd','expert',15,'FOREVER','SEMPRE','SIEMPRE'),
('psalm-121-lifting-my-eyes','balanced',6,'EYES','OLHOS','OJOS'),
('psalm-121-lifting-my-eyes','balanced',7,'SLUMBER','ADORMECE','DORMITA'),
('psalm-121-lifting-my-eyes','balanced',8,'WATCH','VIGIA','VIGILA'),
('psalm-121-lifting-my-eyes','challenging',9,'MOON','LUA','LUNA'),
('psalm-121-lifting-my-eyes','challenging',10,'STUMBLE','TROPEÇAR','TROPEZAR'),
('psalm-121-lifting-my-eyes','challenging',11,'MAKER','CRIADOR','CREADOR'),
('psalm-121-lifting-my-eyes','expert',12,'PRESERVE','PRESERVA','PRESERVA'),
('psalm-121-lifting-my-eyes','expert',13,'COMING','VINDA','VENIDA'),
('psalm-121-lifting-my-eyes','expert',14,'GOING','SAÍDA','SALIDA'),
('psalm-121-lifting-my-eyes','expert',15,'STRENGTH','FORÇA','FUERZA'),
('psalm-46-present-help','balanced',6,'TROUBLE','ANGÚSTIA','ANGUSTIA'),
('psalm-46-present-help','balanced',7,'NATIONS','NAÇÕES','NACIONES'),
('psalm-46-present-help','balanced',8,'CITY','CIDADE','CIUDAD'),
('psalm-46-present-help','challenging',9,'FORTRESS','FORTALEZA','FORTALEZA'),
('psalm-46-present-help','challenging',10,'MOUNTAINS','MONTES','MONTES'),
('psalm-46-present-help','challenging',11,'EXALTED','EXALTADO','EXALTADO'),
('psalm-46-present-help','expert',12,'WATERS','ÁGUAS','AGUAS'),
('psalm-46-present-help','expert',13,'SILENCE','SILÊNCIO','SILENCIO'),
('psalm-46-present-help','expert',14,'COURAGE','CORAGEM','CORAJE'),
('psalm-46-present-help','expert',15,'STEADY','FIRME','FIRME'),
('matthew-5-beatitudes','balanced',6,'MOURN','CHORAM','LLORAN'),
('matthew-5-beatitudes','balanced',7,'COMFORT','CONSOLO','CONSUELO'),
('matthew-5-beatitudes','balanced',8,'PURE','PUROS','PUROS'),
('matthew-5-beatitudes','challenging',9,'RIGHTEOUS','JUSTIÇA','JUSTICIA'),
('matthew-5-beatitudes','challenging',10,'KINGDOM','REINO','REINO'),
('matthew-5-beatitudes','challenging',11,'REJOICE','ALEGRAI','ALEGRAOS'),
('matthew-5-beatitudes','expert',12,'PEACEMAKERS','PACIFICADORES','PACIFICADORES'),
('matthew-5-beatitudes','expert',13,'INHERIT','HERDARÃO','HEREDARAN'),
('matthew-5-beatitudes','expert',14,'REWARD','RECOMPENSA','RECOMPENSA'),
('matthew-5-beatitudes','expert',15,'THIRST','SEDE','SED'),
('john-6-bread-of-life','balanced',6,'HUNGER','FOME','HAMBRE'),
('john-6-bread-of-life','balanced',7,'MANNA','MANÁ','MANÁ'),
('john-6-bread-of-life','balanced',8,'TRUTH','VERDADE','VERDAD'),
('john-6-bread-of-life','challenging',9,'ETERNAL','ETERNA','ETERNA'),
('john-6-bread-of-life','challenging',10,'HEAVEN','CÉUS','CIELO'),
('john-6-bread-of-life','challenging',11,'PROMISE','PROMESSA','PROMESA'),
('john-6-bread-of-life','expert',12,'SATISFY','SACIA','SACIA'),
('john-6-bread-of-life','expert',13,'DISCIPLES','DISCÍPULOS','DISCIPULOS'),
('john-6-bread-of-life','expert',14,'WORDS','PALAVRAS','PALABRAS'),
('john-6-bread-of-life','expert',15,'SPIRIT','ESPÍRITO','ESPÍRITU'),
('john-10-good-shepherd','balanced',6,'SHEPHERD','PASTOR','PASTOR'),
('john-10-good-shepherd','balanced',7,'FLOCK','REBANHO','REBAÑO'),
('john-10-good-shepherd','balanced',8,'KNOWS','CONHECE','CONOCE'),
('john-10-good-shepherd','challenging',9,'PASTURE','PASTAGEM','PASTO'),
('john-10-good-shepherd','challenging',10,'STRANGER','ESTRANHO','EXTRAÑO'),
('john-10-good-shepherd','challenging',11,'ABUNDANT','ABUNDANTE','ABUNDANTE'),
('john-10-good-shepherd','expert',12,'SHELTER','ABRIGO','REFUGIO'),
('john-10-good-shepherd','expert',13,'PROTECT','PROTEGE','PROTEGE'),
('john-10-good-shepherd','expert',14,'CALLS','CHAMA','LLAMA'),
('john-10-good-shepherd','expert',15,'NAME','NOME','NOMBRE'),
('proverbs-3-trust-lean-not','balanced',6,'ACKNOWLEDGE','RECONHECE','RECONOCE'),
('proverbs-3-trust-lean-not','balanced',7,'UNDERSTANDING','ENTENDIMENTO','ENTENDIMIENTO'),
('proverbs-3-trust-lean-not','balanced',8,'FAVOR','FAVOR','FAVOR'),
('proverbs-3-trust-lean-not','challenging',9,'KINDNESS','BONDADE','BONDAD'),
('proverbs-3-trust-lean-not','challenging',10,'TRUTH','VERDADE','VERDAD'),
('proverbs-3-trust-lean-not','challenging',11,'HUMBLE','HUMILDE','HUMILDE'),
('proverbs-3-trust-lean-not','expert',12,'GUIDANCE','DIREÇÃO','DIRECCION'),
('proverbs-3-trust-lean-not','expert',13,'PATIENCE','PACIÊNCIA','PACIENCIA'),
('proverbs-3-trust-lean-not','expert',14,'COUNSEL','CONSELHO','CONSEJO'),
('proverbs-3-trust-lean-not','expert',15,'STEPS','PASSOS','PASOS'),
('proverbs-15-words-that-heal','balanced',6,'HARSH','ÁSPERA','ASPERA'),
('proverbs-15-words-that-heal','balanced',7,'WORDS','PALAVRAS','PALABRAS'),
('proverbs-15-words-that-heal','balanced',8,'HEALING','CURA','CURA'),
('proverbs-15-words-that-heal','challenging',9,'PATIENCE','PACIÊNCIA','PACIENCIA'),
('proverbs-15-words-that-heal','challenging',10,'WISE','SÁBIO','SABIO'),
('proverbs-15-words-that-heal','challenging',11,'QUARREL','CONTENDA','CONTIENDA'),
('proverbs-15-words-that-heal','expert',12,'LISTEN','ESCUTA','ESCUCHA'),
('proverbs-15-words-that-heal','expert',13,'SOOTHE','ACALMA','SUAVIZA'),
('proverbs-15-words-that-heal','expert',14,'SPIRIT','ESPÍRITO','ESPÍRITU'),
('proverbs-15-words-that-heal','expert',15,'TRUTH','VERDADE','VERDAD'),
('proverbs-16-diligent-hand','balanced',6,'PURPOSE','PROPÓSITO','PROPOSITO'),
('proverbs-16-diligent-hand','balanced',7,'STEPS','PASSOS','PASOS'),
('proverbs-16-diligent-hand','balanced',8,'LORD','SENHOR','SEÑOR'),
('proverbs-16-diligent-hand','challenging',9,'ESTABLISH','ESTABELECE','ESTABLECE'),
('proverbs-16-diligent-hand','challenging',10,'HUMBLE','HUMILDE','HUMILDE'),
('proverbs-16-diligent-hand','challenging',11,'PATIENT','PACIENTE','PACIENTE'),
('proverbs-16-diligent-hand','expert',12,'FAITHFUL','FIEL','FIEL'),
('proverbs-16-diligent-hand','expert',13,'GUIDANCE','DIREÇÃO','DIRECCION'),
('proverbs-16-diligent-hand','expert',14,'LABOR','TRABALHO','TRABAJO'),
('proverbs-16-diligent-hand','expert',15,'WISDOM','SABEDORIA','SABIDURIA')
), ins as (
  insert into journey_words (journey_id, position, is_required, is_active, min_difficulty)
  select j.id, s.pos, false, true, s.tier::difficulty_level
  from src s join journeys j on j.slug = s.slug
  where not exists (
    select 1 from journey_words w where w.journey_id = j.id and w.position = s.pos
  )
  returning id, journey_id, position
)
insert into journey_word_translations (journey_word_id, journey_id, language_code, status, display_value, normalized_value)
select i.id, i.journey_id, l.code, 'published'::translation_status, l.display,
       upper(translate(l.display, 'ÁÀÃÂÄÉÊÈËÍÎÌÏÓÔÕÒÖÚÙÛÜÇÑáàãâäéêèëíîìïóôõòöúùûüçñ',
                                  'AAAAAEEEEIIIIOOOOOUUUUCNAAAAAEEEEIIIIOOOOOUUUUCN'))
from ins i
join journeys j on j.id = i.journey_id
join src s on s.slug = j.slug and s.pos = i.position
cross join lateral (values ('en', s.en), ('pt', s.pt), ('es', s.es)) as l(code, display);