import type { WordGuessLocale, WordGuessQuestion } from "./types";

// Development content only — typed, local, and deliberately not wired to
// Supabase. The per-locale map is the extension point for future Portuguese
// and Spanish sets; questionsForLocale falls back to English the same way the
// app's t() does, so an empty locale never blanks the screen.

const EN_QUESTIONS: readonly WordGuessQuestion[] = [
  {
    id: "wg-en-moses",
    locale: "en",
    question: "Who parted the Red Sea?",
    answer: "MOSES",
    scriptureReference: "Exodus 14:21–22",
    hint: "He was raised in Pharaoh's palace.",
    explanation: "Moses stretched out his hand, and the Lord divided the sea for Israel to cross.",
    difficulty: "gentle",
    category: "people",
  },
  {
    id: "wg-en-noah",
    locale: "en",
    question: "Who built the ark?",
    answer: "NOAH",
    scriptureReference: "Genesis 6:13–22",
    hint: "It rained for forty days and forty nights.",
    explanation:
      "Noah built the ark in obedience, and his household was kept safe through the flood.",
    difficulty: "gentle",
    category: "people",
  },
  {
    id: "wg-en-david",
    locale: "en",
    question: "Who defeated Goliath?",
    answer: "DAVID",
    scriptureReference: "1 Samuel 17:45–50",
    hint: "A shepherd boy with a sling and five smooth stones.",
    explanation: "David faced the giant in the name of the Lord and prevailed with a single stone.",
    difficulty: "gentle",
    category: "people",
  },
  {
    id: "wg-en-jonah",
    locale: "en",
    question: "Who was swallowed by a great fish?",
    answer: "JONAH",
    scriptureReference: "Jonah 1:17",
    hint: "He ran from a call to Nineveh.",
    explanation:
      "Jonah spent three days and nights inside the fish before being given a second chance.",
    difficulty: "gentle",
    category: "people",
  },
  {
    id: "wg-en-adam",
    locale: "en",
    question: "Who was the first man?",
    answer: "ADAM",
    scriptureReference: "Genesis 2:7",
    hint: "Formed from the dust of the ground.",
    explanation: "Adam was formed from dust and received the breath of life from God.",
    difficulty: "gentle",
    category: "people",
  },
  {
    id: "wg-en-eve",
    locale: "en",
    question: "Who was the first woman?",
    answer: "EVE",
    scriptureReference: "Genesis 3:20",
    hint: 'Her name means "living".',
    explanation: "Eve was called the mother of all living.",
    difficulty: "gentle",
    category: "people",
  },
  {
    id: "wg-en-joseph",
    locale: "en",
    question: "Who interpreted Pharaoh's dreams?",
    answer: "JOSEPH",
    scriptureReference: "Genesis 41:25–36",
    hint: "His brothers sold him, but God meant it for good.",
    explanation: "Joseph read the dreams as seven years of plenty followed by seven of famine.",
    difficulty: "balanced",
    category: "people",
  },
  {
    id: "wg-en-judas",
    locale: "en",
    question: "Who betrayed Jesus?",
    answer: "JUDAS",
    scriptureReference: "Luke 22:47–48",
    hint: "He handed him over with a kiss.",
    explanation: "Judas Iscariot betrayed Jesus to the authorities for thirty pieces of silver.",
    difficulty: "balanced",
    category: "people",
  },
  {
    id: "wg-en-mary",
    locale: "en",
    question: "Who was the mother of Jesus?",
    answer: "MARY",
    scriptureReference: "Luke 1:30–31",
    hint: "The angel Gabriel brought her the news.",
    explanation:
      'Mary received the angel\'s word with faith: "let it be to me according to your word".',
    difficulty: "balanced",
    category: "people",
  },
  {
    id: "wg-en-john",
    locale: "en",
    question: "Who baptized Jesus?",
    answer: "JOHN",
    scriptureReference: "Matthew 3:13–17",
    hint: "A voice crying in the wilderness.",
    explanation: "John baptized Jesus in the Jordan, and the Spirit descended like a dove.",
    difficulty: "balanced",
    category: "people",
  },
  {
    id: "wg-en-peter",
    locale: "en",
    question: "Who denied Jesus three times?",
    answer: "PETER",
    scriptureReference: "Luke 22:60–62",
    hint: "The rooster crowed, and he remembered.",
    explanation:
      "Peter denied his Lord three times, wept bitterly — and was later restored three times.",
    difficulty: "balanced",
    category: "people",
  },
  {
    id: "wg-en-solomon",
    locale: "en",
    question: "Who was known for great wisdom?",
    answer: "SOLOMON",
    scriptureReference: "1 Kings 3:9–12",
    hint: "He asked God for an understanding heart.",
    explanation: "Solomon asked for wisdom rather than riches, and God granted both.",
    difficulty: "challenging",
    category: "people",
  },
  {
    id: "wg-en-daniel",
    locale: "en",
    question: "Who was thrown into the lions' den?",
    answer: "DANIEL",
    scriptureReference: "Daniel 6:16–23",
    hint: "He kept praying three times a day.",
    explanation: "Daniel was delivered unharmed, for he had trusted in his God.",
    difficulty: "challenging",
    category: "people",
  },
  {
    id: "wg-en-joshua",
    locale: "en",
    question: "Who led the Israelites into the Promised Land?",
    answer: "JOSHUA",
    scriptureReference: "Joshua 1:1–9",
    hint: '"Be strong and courageous."',
    explanation: "Joshua succeeded Moses and led Israel across the Jordan into the land.",
    difficulty: "challenging",
    category: "people",
  },
  {
    id: "wg-en-zacchaeus",
    locale: "en",
    question: "Who climbed a tree to see Jesus?",
    answer: "ZACCHAEUS",
    scriptureReference: "Luke 19:1–10",
    hint: "A short tax collector in Jericho.",
    explanation: "Zacchaeus climbed a sycamore tree, and Jesus called him down by name.",
    difficulty: "challenging",
    category: "people",
  },
  {
    id: "wg-en-holy-spirit",
    locale: "en",
    question: "Who descended at Pentecost with tongues of fire?",
    answer: "HOLY SPIRIT",
    scriptureReference: "Acts 2:1–4",
    hint: "The promised Helper.",
    explanation:
      "At Pentecost the Holy Spirit filled the disciples, and they spoke in other tongues.",
    difficulty: "expert",
    category: "events",
  },
  {
    id: "wg-en-mary-magdalene",
    locale: "en",
    question: "Who first saw the risen Jesus at the tomb?",
    answer: "MARY MAGDALENE",
    scriptureReference: "John 20:11–18",
    hint: "She mistook him for the gardener.",
    explanation:
      'Mary Magdalene met the risen Lord in the garden and announced: "I have seen the Lord".',
    difficulty: "expert",
    category: "people",
  },
  {
    id: "wg-en-noahs-ark",
    locale: "en",
    question: "What vessel carried Noah's family through the flood?",
    answer: "NOAH'S ARK",
    scriptureReference: "Genesis 7:1",
    hint: "Built of gopher wood, sealed with pitch.",
    explanation: "The ark carried Noah's family and the animals safely through the waters.",
    difficulty: "expert",
    category: "places",
  },
];

const PT_QUESTIONS: readonly WordGuessQuestion[] = [
  {
    id: "wg-pt-moises",
    locale: "pt",
    question: "Quem abriu o Mar Vermelho?",
    answer: "MOISÉS",
    scriptureReference: "Êxodo 14:21–22",
    hint: "Cresceu no palácio do faraó.",
    explanation: "Moisés estendeu a mão, e o Senhor dividiu o mar para Israel atravessar.",
    difficulty: "gentle",
    category: "people",
  },
  {
    id: "wg-pt-noe",
    locale: "pt",
    question: "Quem construiu a arca?",
    answer: "NOÉ",
    scriptureReference: "Gênesis 6:13–22",
    hint: "Choveu quarenta dias e quarenta noites.",
    explanation: "Noé construiu a arca em obediência, e sua família foi guardada no dilúvio.",
    difficulty: "gentle",
    category: "people",
  },
  {
    id: "wg-pt-davi",
    locale: "pt",
    question: "Quem venceu Golias?",
    answer: "DAVI",
    scriptureReference: "1 Samuel 17:45–50",
    hint: "Um pastorzinho com uma funda e cinco pedras lisas.",
    explanation: "Davi enfrentou o gigante em nome do Senhor e venceu com uma única pedra.",
    difficulty: "gentle",
    category: "people",
  },
  {
    id: "wg-pt-jonas",
    locale: "pt",
    question: "Quem foi engolido por um grande peixe?",
    answer: "JONAS",
    scriptureReference: "Jonas 1:17",
    hint: "Fugiu de um chamado para Nínive.",
    explanation:
      "Jonas passou três dias e três noites no peixe antes de receber uma segunda chance.",
    difficulty: "gentle",
    category: "people",
  },
  {
    id: "wg-pt-adao",
    locale: "pt",
    question: "Quem foi o primeiro homem?",
    answer: "ADÃO",
    scriptureReference: "Gênesis 2:7",
    hint: "Formado do pó da terra.",
    explanation: "Adão foi formado do pó e recebeu de Deus o fôlego da vida.",
    difficulty: "gentle",
    category: "people",
  },
  {
    id: "wg-pt-eva",
    locale: "pt",
    question: "Quem foi a primeira mulher?",
    answer: "EVA",
    scriptureReference: "Gênesis 3:20",
    hint: 'Seu nome significa "vivente".',
    explanation: "Eva foi chamada mãe de todos os viventes.",
    difficulty: "gentle",
    category: "people",
  },
  {
    id: "wg-pt-jose",
    locale: "pt",
    question: "Quem interpretou os sonhos do faraó?",
    answer: "JOSÉ",
    scriptureReference: "Gênesis 41:25–36",
    hint: "Os irmãos o venderam, mas Deus usou para o bem.",
    explanation: "José leu nos sonhos sete anos de fartura seguidos por sete de fome.",
    difficulty: "balanced",
    category: "people",
  },
  {
    id: "wg-pt-judas",
    locale: "pt",
    question: "Quem traiu Jesus?",
    answer: "JUDAS",
    scriptureReference: "Lucas 22:47–48",
    hint: "Entregou-o com um beijo.",
    explanation: "Judas Iscariotes traiu Jesus por trinta moedas de prata.",
    difficulty: "balanced",
    category: "people",
  },
  {
    id: "wg-pt-maria",
    locale: "pt",
    question: "Quem foi a mãe de Jesus?",
    answer: "MARIA",
    scriptureReference: "Lucas 1:30–31",
    hint: "O anjo Gabriel lhe trouxe a notícia.",
    explanation: 'Maria recebeu a palavra do anjo com fé: "faça-se em mim segundo a tua palavra".',
    difficulty: "balanced",
    category: "people",
  },
  {
    id: "wg-pt-joao",
    locale: "pt",
    question: "Quem batizou Jesus?",
    answer: "JOÃO",
    scriptureReference: "Mateus 3:13–17",
    hint: "Uma voz clamando no deserto.",
    explanation: "João batizou Jesus no Jordão, e o Espírito desceu como pomba.",
    difficulty: "balanced",
    category: "people",
  },
  {
    id: "wg-pt-pedro",
    locale: "pt",
    question: "Quem negou Jesus três vezes?",
    answer: "PEDRO",
    scriptureReference: "Lucas 22:60–62",
    hint: "O galo cantou, e ele se lembrou.",
    explanation:
      "Pedro negou seu Senhor três vezes, chorou amargamente — e depois foi restaurado três vezes.",
    difficulty: "balanced",
    category: "people",
  },
  {
    id: "wg-pt-salomao",
    locale: "pt",
    question: "Quem ficou conhecido pela grande sabedoria?",
    answer: "SALOMÃO",
    scriptureReference: "1 Reis 3:9–12",
    hint: "Pediu a Deus um coração que soubesse entender.",
    explanation: "Salomão pediu sabedoria em vez de riquezas, e Deus lhe deu as duas.",
    difficulty: "challenging",
    category: "people",
  },
  {
    id: "wg-pt-daniel",
    locale: "pt",
    question: "Quem foi lançado na cova dos leões?",
    answer: "DANIEL",
    scriptureReference: "Daniel 6:16–23",
    hint: "Orava três vezes ao dia.",
    explanation: "Daniel saiu ileso, porque confiou no seu Deus.",
    difficulty: "challenging",
    category: "people",
  },
  {
    id: "wg-pt-josue",
    locale: "pt",
    question: "Quem conduziu Israel à Terra Prometida?",
    answer: "JOSUÉ",
    scriptureReference: "Josué 1:1–9",
    hint: '"Sê forte e corajoso."',
    explanation: "Josué sucedeu Moisés e levou Israel a atravessar o Jordão.",
    difficulty: "challenging",
    category: "people",
  },
  {
    id: "wg-pt-zaqueu",
    locale: "pt",
    question: "Quem subiu numa árvore para ver Jesus?",
    answer: "ZAQUEU",
    scriptureReference: "Lucas 19:1–10",
    hint: "Um cobrador de impostos baixinho em Jericó.",
    explanation: "Zaqueu subiu num sicômoro, e Jesus o chamou pelo nome.",
    difficulty: "challenging",
    category: "people",
  },
  {
    id: "wg-pt-espirito-santo",
    locale: "pt",
    question: "Quem desceu no Pentecostes com línguas de fogo?",
    answer: "ESPÍRITO SANTO",
    scriptureReference: "Atos 2:1–4",
    hint: "O Consolador prometido.",
    explanation:
      "No Pentecostes o Espírito Santo encheu os discípulos, e eles falaram em outras línguas.",
    difficulty: "expert",
    category: "events",
  },
  {
    id: "wg-pt-maria-madalena",
    locale: "pt",
    question: "Quem viu primeiro o Jesus ressuscitado junto ao túmulo?",
    answer: "MARIA MADALENA",
    scriptureReference: "João 20:11–18",
    hint: "Ela o confundiu com o jardineiro.",
    explanation:
      'Maria Madalena encontrou o Senhor ressuscitado no jardim e anunciou: "Vi o Senhor".',
    difficulty: "expert",
    category: "people",
  },
  {
    id: "wg-pt-arca-de-noe",
    locale: "pt",
    question: "Que embarcação levou a família de Noé pelo dilúvio?",
    answer: "ARCA DE NOÉ",
    scriptureReference: "Gênesis 7:1",
    hint: "Feita de madeira de gofer, vedada com betume.",
    explanation: "A arca levou em segurança a família de Noé e os animais pelas águas.",
    difficulty: "expert",
    category: "places",
  },
];

const ES_QUESTIONS: readonly WordGuessQuestion[] = [
  {
    id: "wg-es-moises",
    locale: "es",
    question: "¿Quién abrió el Mar Rojo?",
    answer: "MOISÉS",
    scriptureReference: "Éxodo 14:21–22",
    hint: "Creció en el palacio del faraón.",
    explanation: "Moisés extendió su mano, y el Señor dividió el mar para que Israel cruzara.",
    difficulty: "gentle",
    category: "people",
  },
  {
    id: "wg-es-noe",
    locale: "es",
    question: "¿Quién construyó el arca?",
    answer: "NOÉ",
    scriptureReference: "Génesis 6:13–22",
    hint: "Llovió cuarenta días y cuarenta noches.",
    explanation: "Noé construyó el arca en obediencia, y su familia fue guardada en el diluvio.",
    difficulty: "gentle",
    category: "people",
  },
  {
    id: "wg-es-david",
    locale: "es",
    question: "¿Quién venció a Goliat?",
    answer: "DAVID",
    scriptureReference: "1 Samuel 17:45–50",
    hint: "Un joven pastor con una honda y cinco piedras lisas.",
    explanation: "David enfrentó al gigante en el nombre del Señor y venció con una sola piedra.",
    difficulty: "gentle",
    category: "people",
  },
  {
    id: "wg-es-jonas",
    locale: "es",
    question: "¿Quién fue tragado por un gran pez?",
    answer: "JONÁS",
    scriptureReference: "Jonás 1:17",
    hint: "Huyó de un llamado a Nínive.",
    explanation:
      "Jonás pasó tres días y tres noches en el pez antes de recibir una segunda oportunidad.",
    difficulty: "gentle",
    category: "people",
  },
  {
    id: "wg-es-adan",
    locale: "es",
    question: "¿Quién fue el primer hombre?",
    answer: "ADÁN",
    scriptureReference: "Génesis 2:7",
    hint: "Formado del polvo de la tierra.",
    explanation: "Adán fue formado del polvo y recibió de Dios el aliento de vida.",
    difficulty: "gentle",
    category: "people",
  },
  {
    id: "wg-es-eva",
    locale: "es",
    question: "¿Quién fue la primera mujer?",
    answer: "EVA",
    scriptureReference: "Génesis 3:20",
    hint: 'Su nombre significa "viviente".',
    explanation: "Eva fue llamada madre de todos los vivientes.",
    difficulty: "gentle",
    category: "people",
  },
  {
    id: "wg-es-jose",
    locale: "es",
    question: "¿Quién interpretó los sueños del faraón?",
    answer: "JOSÉ",
    scriptureReference: "Génesis 41:25–36",
    hint: "Sus hermanos lo vendieron, pero Dios lo usó para bien.",
    explanation: "José leyó en los sueños siete años de abundancia seguidos de siete de hambre.",
    difficulty: "balanced",
    category: "people",
  },
  {
    id: "wg-es-judas",
    locale: "es",
    question: "¿Quién traicionó a Jesús?",
    answer: "JUDAS",
    scriptureReference: "Lucas 22:47–48",
    hint: "Lo entregó con un beso.",
    explanation: "Judas Iscariote traicionó a Jesús por treinta monedas de plata.",
    difficulty: "balanced",
    category: "people",
  },
  {
    id: "wg-es-maria",
    locale: "es",
    question: "¿Quién fue la madre de Jesús?",
    answer: "MARÍA",
    scriptureReference: "Lucas 1:30–31",
    hint: "El ángel Gabriel le trajo la noticia.",
    explanation:
      'María recibió la palabra del ángel con fe: "hágase conmigo conforme a tu palabra".',
    difficulty: "balanced",
    category: "people",
  },
  {
    id: "wg-es-juan",
    locale: "es",
    question: "¿Quién bautizó a Jesús?",
    answer: "JUAN",
    scriptureReference: "Mateo 3:13–17",
    hint: "Una voz que clama en el desierto.",
    explanation: "Juan bautizó a Jesús en el Jordán, y el Espíritu descendió como paloma.",
    difficulty: "balanced",
    category: "people",
  },
  {
    id: "wg-es-pedro",
    locale: "es",
    question: "¿Quién negó a Jesús tres veces?",
    answer: "PEDRO",
    scriptureReference: "Lucas 22:60–62",
    hint: "El gallo cantó, y él recordó.",
    explanation:
      "Pedro negó a su Señor tres veces, lloró amargamente — y luego fue restaurado tres veces.",
    difficulty: "balanced",
    category: "people",
  },
  {
    id: "wg-es-salomon",
    locale: "es",
    question: "¿Quién fue conocido por su gran sabiduría?",
    answer: "SALOMÓN",
    scriptureReference: "1 Reyes 3:9–12",
    hint: "Pidió a Dios un corazón entendido.",
    explanation: "Salomón pidió sabiduría en lugar de riquezas, y Dios le concedió ambas.",
    difficulty: "challenging",
    category: "people",
  },
  {
    id: "wg-es-daniel",
    locale: "es",
    question: "¿Quién fue arrojado al foso de los leones?",
    answer: "DANIEL",
    scriptureReference: "Daniel 6:16–23",
    hint: "Oraba tres veces al día.",
    explanation: "Daniel salió ileso, porque confió en su Dios.",
    difficulty: "challenging",
    category: "people",
  },
  {
    id: "wg-es-josue",
    locale: "es",
    question: "¿Quién condujo a Israel a la Tierra Prometida?",
    answer: "JOSUÉ",
    scriptureReference: "Josué 1:1–9",
    hint: '"Esfuérzate y sé valiente."',
    explanation: "Josué sucedió a Moisés y llevó a Israel a cruzar el Jordán.",
    difficulty: "challenging",
    category: "people",
  },
  {
    id: "wg-es-zaqueo",
    locale: "es",
    question: "¿Quién subió a un árbol para ver a Jesús?",
    answer: "ZAQUEO",
    scriptureReference: "Lucas 19:1–10",
    hint: "Un cobrador de impuestos de baja estatura en Jericó.",
    explanation: "Zaqueo subió a un sicómoro, y Jesús lo llamó por su nombre.",
    difficulty: "challenging",
    category: "people",
  },
  {
    id: "wg-es-espiritu-santo",
    locale: "es",
    question: "¿Quién descendió en Pentecostés con lenguas de fuego?",
    answer: "ESPÍRITU SANTO",
    scriptureReference: "Hechos 2:1–4",
    hint: "El Consolador prometido.",
    explanation:
      "En Pentecostés el Espíritu Santo llenó a los discípulos, y hablaron en otras lenguas.",
    difficulty: "expert",
    category: "events",
  },
  {
    id: "wg-es-maria-magdalena",
    locale: "es",
    question: "¿Quién vio primero a Jesús resucitado junto al sepulcro?",
    answer: "MARÍA MAGDALENA",
    scriptureReference: "Juan 20:11–18",
    hint: "Lo confundió con el jardinero.",
    explanation:
      'María Magdalena encontró al Señor resucitado en el huerto y anunció: "He visto al Señor".',
    difficulty: "expert",
    category: "people",
  },
  {
    id: "wg-es-arca-de-noe",
    locale: "es",
    question: "¿Qué embarcación llevó a la familia de Noé por el diluvio?",
    answer: "ARCA DE NOÉ",
    scriptureReference: "Génesis 7:1",
    hint: "Hecha de madera de gofer, sellada con brea.",
    explanation: "El arca llevó a salvo a la familia de Noé y a los animales por las aguas.",
    difficulty: "expert",
    category: "places",
  },
];

const QUESTIONS_BY_LOCALE: Record<WordGuessLocale, readonly WordGuessQuestion[]> = {
  en: EN_QUESTIONS,
  pt: PT_QUESTIONS,
  es: ES_QUESTIONS,
};

export function wordGuessQuestionsForLocale(locale: WordGuessLocale): readonly WordGuessQuestion[] {
  const set = QUESTIONS_BY_LOCALE[locale];
  return set.length > 0 ? set : QUESTIONS_BY_LOCALE.en;
}
