import type { WordGuessLocale, WordGuessQuestion } from "./types";

// Development content only — typed, local, and deliberately not wired to
// Supabase. The per-locale map is the extension point for future Portuguese
// and Spanish sets; questionsForLocale falls back to English the same way the
// app's t() does, so an empty locale never blanks the screen.

const EN_QUESTIONS: readonly WordGuessQuestion[] = [
  {
    id: "wg-en-moses",
    locale: "en",
    question: "Who parted the Red Sea?",
    answer: "MOSES",
    scriptureReference: "Exodus 14:21–22",
    hint: "He was raised in Pharaoh's palace.",
    explanation: "Moses stretched out his hand, and the Lord divided the sea for Israel to cross.",
    prayer:
      "Lord who parts the seas, open a way for me where I see none. I will walk through on dry ground.",
    difficulty: "gentle",
    category: "people",
  },
  {
    id: "wg-en-noah",
    locale: "en",
    question: "Who built the ark?",
    answer: "NOAH",
    scriptureReference: "Genesis 6:13–22",
    hint: "It rained for forty days and forty nights.",
    explanation:
      "Noah built the ark in obedience, and his household was kept safe through the flood.",
    prayer:
      "God of the ark, teach me to obey before I understand. Keep me building while the sky is still clear.",
    difficulty: "gentle",
    category: "people",
  },
  {
    id: "wg-en-david",
    locale: "en",
    question: "Who defeated Goliath?",
    answer: "DAVID",
    scriptureReference: "1 Samuel 17:45–50",
    hint: "A shepherd boy with a sling and five smooth stones.",
    explanation: "David faced the giant in the name of the Lord and prevailed with a single stone.",
    prayer:
      "Shepherd of David, you are greater than every giant I face. I come in your name, not my own strength.",
    difficulty: "gentle",
    category: "people",
  },
  {
    id: "wg-en-jonah",
    locale: "en",
    question: "Who was swallowed by a great fish?",
    answer: "JONAH",
    scriptureReference: "Jonah 1:17",
    hint: "He ran from a call to Nineveh.",
    explanation:
      "Jonah spent three days and nights inside the fish before being given a second chance.",
    prayer:
      "God of second calls, when I run from you, run after me. Turn me back toward the place you sent me.",
    difficulty: "gentle",
    category: "people",
  },
  {
    id: "wg-en-adam",
    locale: "en",
    question: "Who was the first man?",
    answer: "ADAM",
    scriptureReference: "Genesis 2:7",
    hint: "Formed from the dust of the ground.",
    explanation: "Adam was formed from dust and received the breath of life from God.",
    prayer:
      "Maker of my dust, you formed me and called it good. Walk with me again in the cool of the day.",
    difficulty: "gentle",
    category: "people",
  },
  {
    id: "wg-en-eve",
    locale: "en",
    question: "Who was the first woman?",
    answer: "EVE",
    scriptureReference: "Genesis 3:20",
    hint: 'Her name means "living".',
    explanation: "Eve was called the mother of all living.",
    prayer:
      "God who clothes the ashamed, cover what I cannot mend. Let your promise outlast my failure.",
    difficulty: "gentle",
    category: "people",
  },
  {
    id: "wg-en-joseph",
    locale: "en",
    question: "Who interpreted Pharaoh's dreams?",
    answer: "JOSEPH",
    scriptureReference: "Genesis 41:25–36",
    hint: "His brothers sold him, but God meant it for good.",
    explanation: "Joseph read the dreams as seven years of plenty followed by seven of famine.",
    prayer:
      "God of Joseph, take what was meant for evil in my story and mean it for good. Keep my heart soft toward those who wronged me.",
    difficulty: "balanced",
    category: "people",
  },
  {
    id: "wg-en-judas",
    locale: "en",
    question: "Who betrayed Jesus?",
    answer: "JUDAS",
    scriptureReference: "Luke 22:47–48",
    hint: "He handed him over with a kiss.",
    explanation: "Judas Iscariot betrayed Jesus to the authorities for thirty pieces of silver.",
    prayer:
      "Search me, Lord, before I trade what is precious for what is passing. Keep me true when no one is watching.",
    difficulty: "balanced",
    category: "people",
  },
  {
    id: "wg-en-mary",
    locale: "en",
    question: "Who was the mother of Jesus?",
    answer: "MARY",
    scriptureReference: "Luke 1:30–31",
    hint: "The angel Gabriel brought her the news.",
    explanation:
      'Mary received the angel\'s word with faith: "let it be to me according to your word".',
    prayer:
      "Lord, let it be to me according to your word. I say yes before I can see the whole road.",
    difficulty: "balanced",
    category: "people",
  },
  {
    id: "wg-en-john",
    locale: "en",
    question: "Who baptized Jesus?",
    answer: "JOHN",
    scriptureReference: "Matthew 3:13–17",
    hint: "A voice crying in the wilderness.",
    explanation: "John baptized Jesus in the Jordan, and the Spirit descended like a dove.",
    prayer:
      "Beloved Lord, let me rest close enough to hear your heart. Teach me to love the way you loved.",
    difficulty: "balanced",
    category: "people",
  },
  {
    id: "wg-en-peter",
    locale: "en",
    question: "Who denied Jesus three times?",
    answer: "PETER",
    scriptureReference: "Luke 22:60–62",
    hint: "The rooster crowed, and he remembered.",
    explanation:
      "Peter denied his Lord three times, wept bitterly — and was later restored three times.",
    prayer:
      "Lord of the shore, you restore the ones who denied you. Ask me again if I love you — and send me to feed your sheep.",
    difficulty: "balanced",
    category: "people",
  },
  {
    id: "wg-en-solomon",
    locale: "en",
    question: "Who was known for great wisdom?",
    answer: "SOLOMON",
    scriptureReference: "1 Kings 3:9–12",
    hint: "He asked God for an understanding heart.",
    explanation: "Solomon asked for wisdom rather than riches, and God granted both.",
    prayer:
      "Giver of wisdom, I ask for an understanding heart before anything else. Let me want what you count precious.",
    difficulty: "challenging",
    category: "people",
  },
  {
    id: "wg-en-daniel",
    locale: "en",
    question: "Who was thrown into the lions' den?",
    answer: "DANIEL",
    scriptureReference: "Daniel 6:16–23",
    hint: "He kept praying three times a day.",
    explanation: "Daniel was delivered unharmed, for he had trusted in his God.",
    prayer:
      "God who shuts the mouths of lions, keep me faithful with my window open. I will not hide whose I am.",
    difficulty: "challenging",
    category: "people",
  },
  {
    id: "wg-en-joshua",
    locale: "en",
    question: "Who led the Israelites into the Promised Land?",
    answer: "JOSHUA",
    scriptureReference: "Joshua 1:1–9",
    hint: '"Be strong and courageous."',
    explanation: "Joshua succeeded Moses and led Israel across the Jordan into the land.",
    prayer:
      "Lord my God, you are with me wherever I go. Make me strong and courageous for the crossing ahead.",
    difficulty: "challenging",
    category: "people",
  },
  {
    id: "wg-en-zacchaeus",
    locale: "en",
    question: "Who climbed a tree to see Jesus?",
    answer: "ZACCHAEUS",
    scriptureReference: "Luke 19:1–10",
    hint: "A short tax collector in Jericho.",
    explanation: "Zacchaeus climbed a sycamore tree, and Jesus called him down by name.",
    prayer:
      "Lord who looks up into trees, call my name today. I will come down quickly and receive you with joy.",
    difficulty: "challenging",
    category: "people",
  },
  {
    id: "wg-en-holy-spirit",
    locale: "en",
    question: "Who descended at Pentecost with tongues of fire?",
    answer: "HOLY SPIRIT",
    scriptureReference: "Acts 2:1–4",
    hint: "The promised Helper.",
    explanation:
      "At Pentecost the Holy Spirit filled the disciples, and they spoke in other tongues.",
    prayer: "Breath of God, fill this house again. Comfort, teach and lead me into all truth.",
    difficulty: "expert",
    category: "events",
  },
  {
    id: "wg-en-mary-magdalene",
    locale: "en",
    question: "Who first saw the risen Jesus at the tomb?",
    answer: "MARY MAGDALENE",
    scriptureReference: "John 20:11–18",
    hint: "She mistook him for the gardener.",
    explanation:
      'Mary Magdalene met the risen Lord in the garden and announced: "I have seen the Lord".',
    prayer: "Risen Lord, speak my name in the garden of my grief. Turn my weeping into witness.",
    difficulty: "expert",
    category: "people",
  },
  {
    id: "wg-en-samson",
    locale: "en",
    question: "Whose strength was betrayed by Delilah?",
    answer: "SAMSON",
    scriptureReference: "Judges 16:17–19",
    hint: "His vow was in his hair.",
    explanation: "Samson's strength returned one last time, and God answered his final prayer.",
    prayer:
      "God of returning strength, hear me at my weakest hour. What I squandered, redeem in one last surrender.",
    difficulty: "balanced",
    category: "people",
  },
  {
    id: "wg-en-abraham",
    locale: "en",
    question: "Who was asked to offer his son on the mountain?",
    answer: "ABRAHAM",
    scriptureReference: "Genesis 22:1–14",
    hint: "He left home without knowing where he was going.",
    explanation:
      "Abraham trusted the God who provides, and on the mountain a ram was given instead.",
    prayer:
      "God who provides on the mountain, I will trust you with what I cannot keep. You are faithful beyond what I can see.",
    difficulty: "balanced",
    category: "people",
  },
  {
    id: "wg-en-sarah",
    locale: "en",
    question: "Who laughed when told she would have a son?",
    answer: "SARAH",
    scriptureReference: "Genesis 18:12–14",
    hint: "Her son's name means laughter.",
    explanation:
      "Sarah laughed at the promise, and the son of that promise was named Isaac — laughter.",
    prayer:
      "Lord of impossible promises, turn my unbelieving laughter into joy. Nothing is too hard for you.",
    difficulty: "balanced",
    category: "people",
  },
  {
    id: "wg-en-esther",
    locale: "en",
    question: "Which queen risked her life to save her people?",
    answer: "ESTHER",
    scriptureReference: "Esther 4:14",
    hint: '"For such a time as this."',
    explanation: "Esther went before the king uninvited, and her people were spared.",
    prayer:
      "God of such a time as this, give me courage that begins on its knees. If I perish, I perish — but I will go.",
    difficulty: "balanced",
    category: "people",
  },
  {
    id: "wg-en-ruth",
    locale: "en",
    question: 'Who said "where you go, I will go"?',
    answer: "RUTH",
    scriptureReference: "Ruth 1:16",
    hint: "A Moabite who gleaned in the fields of Boaz.",
    explanation:
      "Ruth chose Naomi's people and Naomi's God, and became great-grandmother of David.",
    prayer:
      "God of Ruth, where you go I will go. Make my small daily faithfulness part of your long story.",
    difficulty: "gentle",
    category: "people",
  },
  {
    id: "wg-en-elijah",
    locale: "en",
    question: "Who was taken up in a chariot of fire?",
    answer: "ELIJAH",
    scriptureReference: "2 Kings 2:11",
    hint: "Ravens fed him by the brook.",
    explanation: "Elijah went up by a whirlwind into heaven, and Elisha received his mantle.",
    prayer:
      "God of the still small voice, feed me when I am spent. Speak after the wind, and I will listen.",
    difficulty: "challenging",
    category: "people",
  },
  {
    id: "wg-en-goliath",
    locale: "en",
    question: "Which giant of Gath defied the armies of Israel?",
    answer: "GOLIATH",
    scriptureReference: "1 Samuel 17:4–11",
    hint: "He fell to a shepherd's sling.",
    explanation: "Goliath trusted armour and spear; David came in the name of the Lord of hosts.",
    prayer:
      "Lord of hosts, the battle is yours. I face what towers over me with five smooth stones and your name.",
    difficulty: "challenging",
    category: "people",
  },
  {
    id: "wg-en-bethlehem",
    locale: "en",
    question: "In which town was Jesus born?",
    answer: "BETHLEHEM",
    scriptureReference: "Luke 2:4–7",
    hint: "The city of David, small among the towns of Judah.",
    explanation: "In Bethlehem — the house of bread — the Bread of Life was laid in a manger.",
    prayer:
      "Bread of Life, born in the house of bread, be born in my small place too. No town is too little for you.",
    difficulty: "challenging",
    category: "places",
  },
  {
    id: "wg-en-jericho",
    locale: "en",
    question: "Which city's walls fell after seven days?",
    answer: "JERICHO",
    scriptureReference: "Joshua 6:20",
    hint: "They marched, and on the seventh day they shouted.",
    explanation: "The walls of Jericho fell flat, and Israel took the city as the Lord had said.",
    prayer:
      "God who levels walls, I will keep walking and keep silent until you say shout. Bring down what shuts me out.",
    difficulty: "challenging",
    category: "places",
  },
  {
    id: "wg-en-lazarus",
    locale: "en",
    question: "Who was raised after four days in the tomb?",
    answer: "LAZARUS",
    scriptureReference: "John 11:43–44",
    hint: "Jesus wept before calling his name.",
    explanation: "Jesus called with a loud voice, and the man who had died came out.",
    prayer:
      "Lord who weeps and then calls, speak into my tomb. Unbind me, and let me walk out into the light.",
    difficulty: "challenging",
    category: "people",
  },
  {
    id: "wg-en-thomas",
    locale: "en",
    question: "Which disciple doubted until he saw?",
    answer: "THOMAS",
    scriptureReference: "John 20:27–28",
    hint: '"My Lord and my God!"',
    explanation: "Thomas doubted, then confessed more fully than any of them.",
    prayer:
      "My Lord and my God, meet my doubt with your scars. Blessed are those who believe without seeing — make me one of them.",
    difficulty: "expert",
    category: "people",
  },
  {
    id: "wg-en-gabriel",
    locale: "en",
    question: "Which angel announced the birth of Jesus to Mary?",
    answer: "GABRIEL",
    scriptureReference: "Luke 1:26–31",
    hint: "He also visited Zechariah in the temple.",
    explanation: "Gabriel was sent from God to Nazareth, to a virgin named Mary.",
    prayer:
      "God who sends word, find me where I am with news of grace. Nothing you say will be impossible.",
    difficulty: "expert",
    category: "people",
  },
  {
    id: "wg-en-noahs-ark",
    locale: "en",
    question: "What vessel carried Noah's family through the flood?",
    answer: "NOAH'S ARK",
    scriptureReference: "Genesis 7:1",
    hint: "Built of gopher wood, sealed with pitch.",
    explanation: "The ark carried Noah's family and the animals safely through the waters.",
    prayer:
      "God of the covenant, shut the door behind me and keep me through the storm. Set your bow in my clouds.",
    difficulty: "expert",
    category: "places",
  },
];

const PT_QUESTIONS: readonly WordGuessQuestion[] = [
  {
    id: "wg-pt-moises",
    locale: "pt",
    question: "Quem abriu o Mar Vermelho?",
    answer: "MOISÉS",
    scriptureReference: "Êxodo 14:21–22",
    hint: "Cresceu no palácio do faraó.",
    explanation: "Moisés estendeu a mão, e o Senhor dividiu o mar para Israel atravessar.",
    prayer:
      "Senhor que abre o mar, abre caminho para mim onde não vejo nenhum. Atravessarei em terra seca.",
    difficulty: "gentle",
    category: "people",
  },
  {
    id: "wg-pt-noe",
    locale: "pt",
    question: "Quem construiu a arca?",
    answer: "NOÉ",
    scriptureReference: "Gênesis 6:13–22",
    hint: "Choveu quarenta dias e quarenta noites.",
    explanation: "Noé construiu a arca em obediência, e sua família foi guardada no dilúvio.",
    prayer:
      "Deus da arca, ensina-me a obedecer antes de entender. Que eu continue construindo enquanto o céu ainda está limpo.",
    difficulty: "gentle",
    category: "people",
  },
  {
    id: "wg-pt-davi",
    locale: "pt",
    question: "Quem venceu Golias?",
    answer: "DAVI",
    scriptureReference: "1 Samuel 17:45–50",
    hint: "Um pastorzinho com uma funda e cinco pedras lisas.",
    explanation: "Davi enfrentou o gigante em nome do Senhor e venceu com uma única pedra.",
    prayer:
      "Pastor de Davi, tu és maior que todo gigante que enfrento. Venho em teu nome, não na minha força.",
    difficulty: "gentle",
    category: "people",
  },
  {
    id: "wg-pt-jonas",
    locale: "pt",
    question: "Quem foi engolido por um grande peixe?",
    answer: "JONAS",
    scriptureReference: "Jonas 1:17",
    hint: "Fugiu de um chamado para Nínive.",
    explanation:
      "Jonas passou três dias e três noites no peixe antes de receber uma segunda chance.",
    prayer:
      "Deus da segunda chamada, quando eu fugir de ti, corre atrás de mim. Faze-me voltar ao lugar para onde me enviaste.",
    difficulty: "gentle",
    category: "people",
  },
  {
    id: "wg-pt-adao",
    locale: "pt",
    question: "Quem foi o primeiro homem?",
    answer: "ADÃO",
    scriptureReference: "Gênesis 2:7",
    hint: "Formado do pó da terra.",
    explanation: "Adão foi formado do pó e recebeu de Deus o fôlego da vida.",
    prayer:
      "Criador do meu pó, tu me formaste e chamaste isso de bom. Caminha comigo de novo na viração do dia.",
    difficulty: "gentle",
    category: "people",
  },
  {
    id: "wg-pt-eva",
    locale: "pt",
    question: "Quem foi a primeira mulher?",
    answer: "EVA",
    scriptureReference: "Gênesis 3:20",
    hint: 'Seu nome significa "vivente".',
    explanation: "Eva foi chamada mãe de todos os viventes.",
    prayer:
      "Deus que veste os envergonhados, cobre o que não consigo consertar. Que a tua promessa dure mais que a minha falha.",
    difficulty: "gentle",
    category: "people",
  },
  {
    id: "wg-pt-jose",
    locale: "pt",
    question: "Quem interpretou os sonhos do faraó?",
    answer: "JOSÉ",
    scriptureReference: "Gênesis 41:25–36",
    hint: "Os irmãos o venderam, mas Deus usou para o bem.",
    explanation: "José leu nos sonhos sete anos de fartura seguidos por sete de fome.",
    prayer:
      "Deus de José, toma o que na minha história foi pensado para o mal e transforma em bem. Guarda meu coração brando com quem me feriu.",
    difficulty: "balanced",
    category: "people",
  },
  {
    id: "wg-pt-judas",
    locale: "pt",
    question: "Quem traiu Jesus?",
    answer: "JUDAS",
    scriptureReference: "Lucas 22:47–48",
    hint: "Entregou-o com um beijo.",
    explanation: "Judas Iscariotes traiu Jesus por trinta moedas de prata.",
    prayer:
      "Sonda-me, Senhor, antes que eu troque o precioso pelo passageiro. Guarda-me fiel quando ninguém está olhando.",
    difficulty: "balanced",
    category: "people",
  },
  {
    id: "wg-pt-maria",
    locale: "pt",
    question: "Quem foi a mãe de Jesus?",
    answer: "MARIA",
    scriptureReference: "Lucas 1:30–31",
    hint: "O anjo Gabriel lhe trouxe a notícia.",
    explanation: 'Maria recebeu a palavra do anjo com fé: "faça-se em mim segundo a tua palavra".',
    prayer:
      "Senhor, faça-se em mim segundo a tua palavra. Digo sim antes de enxergar a estrada inteira.",
    difficulty: "balanced",
    category: "people",
  },
  {
    id: "wg-pt-joao",
    locale: "pt",
    question: "Quem batizou Jesus?",
    answer: "JOÃO",
    scriptureReference: "Mateus 3:13–17",
    hint: "Uma voz clamando no deserto.",
    explanation: "João batizou Jesus no Jordão, e o Espírito desceu como pomba.",
    prayer:
      "Senhor amado, deixa-me descansar perto o bastante para ouvir teu coração. Ensina-me a amar como tu amaste.",
    difficulty: "balanced",
    category: "people",
  },
  {
    id: "wg-pt-pedro",
    locale: "pt",
    question: "Quem negou Jesus três vezes?",
    answer: "PEDRO",
    scriptureReference: "Lucas 22:60–62",
    hint: "O galo cantou, e ele se lembrou.",
    explanation:
      "Pedro negou seu Senhor três vezes, chorou amargamente — e depois foi restaurado três vezes.",
    prayer:
      "Senhor da praia, tu restauras os que te negaram. Pergunta-me de novo se eu te amo — e envia-me a cuidar das tuas ovelhas.",
    difficulty: "balanced",
    category: "people",
  },
  {
    id: "wg-pt-salomao",
    locale: "pt",
    question: "Quem ficou conhecido pela grande sabedoria?",
    answer: "SALOMÃO",
    scriptureReference: "1 Reis 3:9–12",
    hint: "Pediu a Deus um coração que soubesse entender.",
    explanation: "Salomão pediu sabedoria em vez de riquezas, e Deus lhe deu as duas.",
    prayer:
      "Doador da sabedoria, peço um coração que saiba entender antes de qualquer outra coisa. Que eu queira o que tu chamas precioso.",
    difficulty: "challenging",
    category: "people",
  },
  {
    id: "wg-pt-daniel",
    locale: "pt",
    question: "Quem foi lançado na cova dos leões?",
    answer: "DANIEL",
    scriptureReference: "Daniel 6:16–23",
    hint: "Orava três vezes ao dia.",
    explanation: "Daniel saiu ileso, porque confiou no seu Deus.",
    prayer:
      "Deus que fecha a boca dos leões, guarda-me fiel com a janela aberta. Não vou esconder de quem eu sou.",
    difficulty: "challenging",
    category: "people",
  },
  {
    id: "wg-pt-josue",
    locale: "pt",
    question: "Quem conduziu Israel à Terra Prometida?",
    answer: "JOSUÉ",
    scriptureReference: "Josué 1:1–9",
    hint: '"Sê forte e corajoso."',
    explanation: "Josué sucedeu Moisés e levou Israel a atravessar o Jordão.",
    prayer:
      "Senhor meu Deus, tu estás comigo por onde eu andar. Faze-me forte e corajoso para a travessia que vem.",
    difficulty: "challenging",
    category: "people",
  },
  {
    id: "wg-pt-zaqueu",
    locale: "pt",
    question: "Quem subiu numa árvore para ver Jesus?",
    answer: "ZAQUEU",
    scriptureReference: "Lucas 19:1–10",
    hint: "Um cobrador de impostos baixinho em Jericó.",
    explanation: "Zaqueu subiu num sicômoro, e Jesus o chamou pelo nome.",
    prayer:
      "Senhor que olha para cima nas árvores, chama meu nome hoje. Descerei depressa e te receberei com alegria.",
    difficulty: "challenging",
    category: "people",
  },
  {
    id: "wg-pt-espirito-santo",
    locale: "pt",
    question: "Quem desceu no Pentecostes com línguas de fogo?",
    answer: "ESPÍRITO SANTO",
    scriptureReference: "Atos 2:1–4",
    hint: "O Consolador prometido.",
    explanation:
      "No Pentecostes o Espírito Santo encheu os discípulos, e eles falaram em outras línguas.",
    prayer: "Sopro de Deus, enche esta casa de novo. Consola, ensina e guia-me em toda a verdade.",
    difficulty: "expert",
    category: "events",
  },
  {
    id: "wg-pt-maria-madalena",
    locale: "pt",
    question: "Quem viu primeiro o Jesus ressuscitado junto ao túmulo?",
    answer: "MARIA MADALENA",
    scriptureReference: "João 20:11–18",
    hint: "Ela o confundiu com o jardineiro.",
    explanation:
      'Maria Madalena encontrou o Senhor ressuscitado no jardim e anunciou: "Vi o Senhor".',
    prayer:
      "Senhor ressurreto, dize meu nome no jardim da minha dor. Transforma meu choro em testemunho.",
    difficulty: "expert",
    category: "people",
  },
  {
    id: "wg-pt-sansao",
    locale: "pt",
    question: "Quem teve a força traída por Dalila?",
    answer: "SANSÃO",
    scriptureReference: "Juízes 16:17–19",
    hint: "Seu voto estava nos cabelos.",
    explanation: "A força de Sansão voltou uma última vez, e Deus respondeu à sua oração final.",
    prayer:
      "Deus da força que volta, ouve-me na minha hora mais fraca. O que desperdicei, redime numa última entrega.",
    difficulty: "balanced",
    category: "people",
  },
  {
    id: "wg-pt-abraao",
    locale: "pt",
    question: "A quem foi pedido oferecer o filho no monte?",
    answer: "ABRAÃO",
    scriptureReference: "Gênesis 22:1–14",
    hint: "Saiu de casa sem saber para onde ia.",
    explanation:
      "Abraão confiou no Deus que provê, e no monte um cordeiro foi dado em lugar do filho.",
    prayer:
      "Deus que provê no monte, confio a ti o que não posso reter. Tu és fiel além do que consigo ver.",
    difficulty: "balanced",
    category: "people",
  },
  {
    id: "wg-pt-sara",
    locale: "pt",
    question: "Quem riu ao ouvir que teria um filho?",
    answer: "SARA",
    scriptureReference: "Gênesis 18:12–14",
    hint: "O nome do filho significa riso.",
    explanation: "Sara riu da promessa, e o filho dessa promessa recebeu o nome de Isaque — riso.",
    prayer:
      "Senhor das promessas impossíveis, transforma meu riso incrédulo em alegria. Nada é difícil demais para ti.",
    difficulty: "balanced",
    category: "people",
  },
  {
    id: "wg-pt-ester",
    locale: "pt",
    question: "Que rainha arriscou a vida para salvar seu povo?",
    answer: "ESTER",
    scriptureReference: "Ester 4:14",
    hint: "Para um tempo como este.",
    explanation: "Ester foi diante do rei sem ser chamada, e seu povo foi poupado.",
    prayer:
      "Deus de um tempo como este, dá-me coragem que começa de joelhos. Se eu perecer, pereci — mas eu irei.",
    difficulty: "balanced",
    category: "people",
  },
  {
    id: "wg-pt-rute",
    locale: "pt",
    question: "Quem disse: aonde quer que fores, irei?",
    answer: "RUTE",
    scriptureReference: "Rute 1:16",
    hint: "Uma moabita que colhia nos campos de Boaz.",
    explanation: "Rute escolheu o povo e o Deus de Noemi, e tornou-se bisavó de Davi.",
    prayer:
      "Deus de Rute, aonde fores, irei. Faze da minha fidelidade pequena de cada dia parte da tua longa história.",
    difficulty: "gentle",
    category: "people",
  },
  {
    id: "wg-pt-elias",
    locale: "pt",
    question: "Quem foi levado num carro de fogo?",
    answer: "ELIAS",
    scriptureReference: "2 Reis 2:11",
    hint: "Corvos o alimentavam junto ao ribeiro.",
    explanation: "Elias subiu ao céu num redemoinho, e Eliseu recebeu seu manto.",
    prayer:
      "Deus da voz mansa e delicada, alimenta-me quando eu estiver esgotado. Fala depois do vento, e eu ouvirei.",
    difficulty: "challenging",
    category: "people",
  },
  {
    id: "wg-pt-golias",
    locale: "pt",
    question: "Que gigante de Gate desafiou os exércitos de Israel?",
    answer: "GOLIAS",
    scriptureReference: "1 Samuel 17:4–11",
    hint: "Caiu diante da funda de um pastor.",
    explanation:
      "Golias confiou na armadura e na lança; Davi veio em nome do Senhor dos Exércitos.",
    prayer:
      "Senhor dos Exércitos, a batalha é tua. Enfrento o que se levanta sobre mim com cinco pedras lisas e o teu nome.",
    difficulty: "challenging",
    category: "people",
  },
  {
    id: "wg-pt-belem",
    locale: "pt",
    question: "Em que cidade Jesus nasceu?",
    answer: "BELÉM",
    scriptureReference: "Lucas 2:4–7",
    hint: "A cidade de Davi, pequena entre as de Judá.",
    explanation: "Em Belém — casa do pão — o Pão da Vida foi deitado numa manjedoura.",
    prayer:
      "Pão da Vida, nascido na casa do pão, nasce também no meu lugar pequeno. Nenhuma cidade é pequena demais para ti.",
    difficulty: "challenging",
    category: "places",
  },
  {
    id: "wg-pt-jerico",
    locale: "pt",
    question: "De que cidade caíram os muros depois de sete dias?",
    answer: "JERICÓ",
    scriptureReference: "Josué 6:20",
    hint: "Marcharam, e no sétimo dia gritaram.",
    explanation: "Os muros de Jericó caíram, e Israel tomou a cidade como o Senhor havia dito.",
    prayer:
      "Deus que derruba muralhas, continuarei andando e calado até dizeres: gritai. Derruba o que me mantém do lado de fora.",
    difficulty: "challenging",
    category: "places",
  },
  {
    id: "wg-pt-lazaro",
    locale: "pt",
    question: "Quem foi ressuscitado depois de quatro dias no túmulo?",
    answer: "LÁZARO",
    scriptureReference: "João 11:43–44",
    hint: "Jesus chorou antes de chamar seu nome.",
    explanation: "Jesus clamou em alta voz, e o que estava morto saiu.",
    prayer:
      "Senhor que chora e depois chama, fala dentro do meu túmulo. Desata-me, e que eu saia para a luz.",
    difficulty: "challenging",
    category: "people",
  },
  {
    id: "wg-pt-tome",
    locale: "pt",
    question: "Que discípulo duvidou até ver?",
    answer: "TOMÉ",
    scriptureReference: "João 20:27–28",
    hint: "Senhor meu, e Deus meu!",
    explanation: "Tomé duvidou e depois confessou mais plenamente do que qualquer outro.",
    prayer:
      "Senhor meu e Deus meu, encontra minha dúvida com as tuas marcas. Bem-aventurados os que creem sem ver — faze-me um deles.",
    difficulty: "expert",
    category: "people",
  },
  {
    id: "wg-pt-gabriel",
    locale: "pt",
    question: "Que anjo anunciou a Maria o nascimento de Jesus?",
    answer: "GABRIEL",
    scriptureReference: "Lucas 1:26–31",
    hint: "Também visitou Zacarias no templo.",
    explanation: "Gabriel foi enviado por Deus a Nazaré, a uma virgem chamada Maria.",
    prayer:
      "Deus que envia palavra, encontra-me onde estou com notícias de graça. Nada do que dizes será impossível.",
    difficulty: "expert",
    category: "people",
  },
  {
    id: "wg-pt-arca-de-noe",
    locale: "pt",
    question: "Que embarcação levou a família de Noé pelo dilúvio?",
    answer: "ARCA DE NOÉ",
    scriptureReference: "Gênesis 7:1",
    hint: "Feita de madeira de gofer, vedada com betume.",
    explanation: "A arca levou em segurança a família de Noé e os animais pelas águas.",
    prayer:
      "Deus da aliança, fecha a porta atrás de mim e guarda-me na tempestade. Põe teu arco nas minhas nuvens.",
    difficulty: "expert",
    category: "places",
  },
];

const ES_QUESTIONS: readonly WordGuessQuestion[] = [
  {
    id: "wg-es-moises",
    locale: "es",
    question: "¿Quién abrió el Mar Rojo?",
    answer: "MOISÉS",
    scriptureReference: "Éxodo 14:21–22",
    hint: "Creció en el palacio del faraón.",
    explanation: "Moisés extendió su mano, y el Señor dividió el mar para que Israel cruzara.",
    prayer:
      "Señor que abres el mar, abre camino para mí donde no veo ninguno. Cruzaré en tierra seca.",
    difficulty: "gentle",
    category: "people",
  },
  {
    id: "wg-es-noe",
    locale: "es",
    question: "¿Quién construyó el arca?",
    answer: "NOÉ",
    scriptureReference: "Génesis 6:13–22",
    hint: "Llovió cuarenta días y cuarenta noches.",
    explanation: "Noé construyó el arca en obediencia, y su familia fue guardada en el diluvio.",
    prayer:
      "Dios del arca, enséñame a obedecer antes de entender. Que siga construyendo mientras el cielo aún está despejado.",
    difficulty: "gentle",
    category: "people",
  },
  {
    id: "wg-es-david",
    locale: "es",
    question: "¿Quién venció a Goliat?",
    answer: "DAVID",
    scriptureReference: "1 Samuel 17:45–50",
    hint: "Un joven pastor con una honda y cinco piedras lisas.",
    explanation: "David enfrentó al gigante en el nombre del Señor y venció con una sola piedra.",
    prayer:
      "Pastor de David, eres más grande que todo gigante que enfrento. Vengo en tu nombre, no en mi fuerza.",
    difficulty: "gentle",
    category: "people",
  },
  {
    id: "wg-es-jonas",
    locale: "es",
    question: "¿Quién fue tragado por un gran pez?",
    answer: "JONÁS",
    scriptureReference: "Jonás 1:17",
    hint: "Huyó de un llamado a Nínive.",
    explanation:
      "Jonás pasó tres días y tres noches en el pez antes de recibir una segunda oportunidad.",
    prayer:
      "Dios de la segunda llamada, cuando huya de ti, corre tras de mí. Hazme volver al lugar adonde me enviaste.",
    difficulty: "gentle",
    category: "people",
  },
  {
    id: "wg-es-adan",
    locale: "es",
    question: "¿Quién fue el primer hombre?",
    answer: "ADÁN",
    scriptureReference: "Génesis 2:7",
    hint: "Formado del polvo de la tierra.",
    explanation: "Adán fue formado del polvo y recibió de Dios el aliento de vida.",
    prayer:
      "Hacedor de mi polvo, me formaste y lo llamaste bueno. Camina conmigo otra vez al aire del día.",
    difficulty: "gentle",
    category: "people",
  },
  {
    id: "wg-es-eva",
    locale: "es",
    question: "¿Quién fue la primera mujer?",
    answer: "EVA",
    scriptureReference: "Génesis 3:20",
    hint: 'Su nombre significa "viviente".',
    explanation: "Eva fue llamada madre de todos los vivientes.",
    prayer:
      "Dios que vistes al avergonzado, cubre lo que no puedo reparar. Que tu promesa dure más que mi caída.",
    difficulty: "gentle",
    category: "people",
  },
  {
    id: "wg-es-jose",
    locale: "es",
    question: "¿Quién interpretó los sueños del faraón?",
    answer: "JOSÉ",
    scriptureReference: "Génesis 41:25–36",
    hint: "Sus hermanos lo vendieron, pero Dios lo usó para bien.",
    explanation: "José leyó en los sueños siete años de abundancia seguidos de siete de hambre.",
    prayer:
      "Dios de José, toma lo que en mi historia se pensó para mal y conviértelo en bien. Guarda mi corazón blando con quien me hirió.",
    difficulty: "balanced",
    category: "people",
  },
  {
    id: "wg-es-judas",
    locale: "es",
    question: "¿Quién traicionó a Jesús?",
    answer: "JUDAS",
    scriptureReference: "Lucas 22:47–48",
    hint: "Lo entregó con un beso.",
    explanation: "Judas Iscariote traicionó a Jesús por treinta monedas de plata.",
    prayer:
      "Escudríñame, Señor, antes de que cambie lo precioso por lo pasajero. Guárdame fiel cuando nadie mira.",
    difficulty: "balanced",
    category: "people",
  },
  {
    id: "wg-es-maria",
    locale: "es",
    question: "¿Quién fue la madre de Jesús?",
    answer: "MARÍA",
    scriptureReference: "Lucas 1:30–31",
    hint: "El ángel Gabriel le trajo la noticia.",
    explanation:
      'María recibió la palabra del ángel con fe: "hágase conmigo conforme a tu palabra".',
    prayer: "Señor, hágase en mí conforme a tu palabra. Digo sí antes de ver todo el camino.",
    difficulty: "balanced",
    category: "people",
  },
  {
    id: "wg-es-juan",
    locale: "es",
    question: "¿Quién bautizó a Jesús?",
    answer: "JUAN",
    scriptureReference: "Mateo 3:13–17",
    hint: "Una voz que clama en el desierto.",
    explanation: "Juan bautizó a Jesús en el Jordán, y el Espíritu descendió como paloma.",
    prayer:
      "Señor amado, déjame descansar lo bastante cerca para oír tu corazón. Enséñame a amar como tú amaste.",
    difficulty: "balanced",
    category: "people",
  },
  {
    id: "wg-es-pedro",
    locale: "es",
    question: "¿Quién negó a Jesús tres veces?",
    answer: "PEDRO",
    scriptureReference: "Lucas 22:60–62",
    hint: "El gallo cantó, y él recordó.",
    explanation:
      "Pedro negó a su Señor tres veces, lloró amargamente — y luego fue restaurado tres veces.",
    prayer:
      "Señor de la orilla, tú restauras a los que te negaron. Pregúntame otra vez si te amo — y envíame a cuidar tus ovejas.",
    difficulty: "balanced",
    category: "people",
  },
  {
    id: "wg-es-salomon",
    locale: "es",
    question: "¿Quién fue conocido por su gran sabiduría?",
    answer: "SALOMÓN",
    scriptureReference: "1 Reyes 3:9–12",
    hint: "Pidió a Dios un corazón entendido.",
    explanation: "Salomón pidió sabiduría en lugar de riquezas, y Dios le concedió ambas.",
    prayer:
      "Dador de sabiduría, pido un corazón entendido antes que cualquier otra cosa. Que quiera lo que tú llamas precioso.",
    difficulty: "challenging",
    category: "people",
  },
  {
    id: "wg-es-daniel",
    locale: "es",
    question: "¿Quién fue arrojado al foso de los leones?",
    answer: "DANIEL",
    scriptureReference: "Daniel 6:16–23",
    hint: "Oraba tres veces al día.",
    explanation: "Daniel salió ileso, porque confió en su Dios.",
    prayer:
      "Dios que cierra la boca de los leones, guárdame fiel con la ventana abierta. No esconderé de quién soy.",
    difficulty: "challenging",
    category: "people",
  },
  {
    id: "wg-es-josue",
    locale: "es",
    question: "¿Quién condujo a Israel a la Tierra Prometida?",
    answer: "JOSUÉ",
    scriptureReference: "Josué 1:1–9",
    hint: '"Esfuérzate y sé valiente."',
    explanation: "Josué sucedió a Moisés y llevó a Israel a cruzar el Jordán.",
    prayer:
      "Señor mi Dios, tú estás conmigo dondequiera que vaya. Hazme fuerte y valiente para el cruce que viene.",
    difficulty: "challenging",
    category: "people",
  },
  {
    id: "wg-es-zaqueo",
    locale: "es",
    question: "¿Quién subió a un árbol para ver a Jesús?",
    answer: "ZAQUEO",
    scriptureReference: "Lucas 19:1–10",
    hint: "Un cobrador de impuestos de baja estatura en Jericó.",
    explanation: "Zaqueo subió a un sicómoro, y Jesús lo llamó por su nombre.",
    prayer:
      "Señor que mira hacia arriba a los árboles, llama mi nombre hoy. Bajaré de prisa y te recibiré con gozo.",
    difficulty: "challenging",
    category: "people",
  },
  {
    id: "wg-es-espiritu-santo",
    locale: "es",
    question: "¿Quién descendió en Pentecostés con lenguas de fuego?",
    answer: "ESPÍRITU SANTO",
    scriptureReference: "Hechos 2:1–4",
    hint: "El Consolador prometido.",
    explanation:
      "En Pentecostés el Espíritu Santo llenó a los discípulos, y hablaron en otras lenguas.",
    prayer: "Aliento de Dios, llena esta casa otra vez. Consuela, enseña y guíame a toda verdad.",
    difficulty: "expert",
    category: "events",
  },
  {
    id: "wg-es-maria-magdalena",
    locale: "es",
    question: "¿Quién vio primero a Jesús resucitado junto al sepulcro?",
    answer: "MARÍA MAGDALENA",
    scriptureReference: "Juan 20:11–18",
    hint: "Lo confundió con el jardinero.",
    explanation:
      'María Magdalena encontró al Señor resucitado en el huerto y anunció: "He visto al Señor".',
    prayer:
      "Señor resucitado, di mi nombre en el huerto de mi dolor. Convierte mi llanto en testimonio.",
    difficulty: "expert",
    category: "people",
  },
  {
    id: "wg-es-sanson",
    locale: "es",
    question: "¿A quién le traicionó su fuerza por causa de Dalila?",
    answer: "SANSÓN",
    scriptureReference: "Jueces 16:17–19",
    hint: "Su voto estaba en sus cabellos.",
    explanation: "La fuerza de Sansón volvió una última vez, y Dios respondió su oración final.",
    prayer:
      "Dios de la fuerza que vuelve, óyeme en mi hora más débil. Lo que malgasté, redímelo en una última entrega.",
    difficulty: "balanced",
    category: "people",
  },
  {
    id: "wg-es-abraham",
    locale: "es",
    question: "¿A quién se le pidió ofrecer a su hijo en el monte?",
    answer: "ABRAHAM",
    scriptureReference: "Génesis 22:1–14",
    hint: "Salió de su casa sin saber a dónde iba.",
    explanation:
      "Abraham confió en el Dios que provee, y en el monte fue dado un carnero en lugar del hijo.",
    prayer:
      "Dios que provee en el monte, te confío lo que no puedo retener. Eres fiel más allá de lo que veo.",
    difficulty: "balanced",
    category: "people",
  },
  {
    id: "wg-es-sara",
    locale: "es",
    question: "¿Quién se rió al oír que tendría un hijo?",
    answer: "SARA",
    scriptureReference: "Génesis 18:12–14",
    hint: "El nombre del hijo significa risa.",
    explanation: "Sara se rió de la promesa, y el hijo de esa promesa se llamó Isaac — risa.",
    prayer:
      "Señor de las promesas imposibles, convierte mi risa incrédula en gozo. Nada es demasiado difícil para ti.",
    difficulty: "balanced",
    category: "people",
  },
  {
    id: "wg-es-ester",
    locale: "es",
    question: "¿Qué reina arriesgó su vida para salvar a su pueblo?",
    answer: "ESTER",
    scriptureReference: "Ester 4:14",
    hint: "Para esta hora.",
    explanation: "Ester se presentó ante el rey sin ser llamada, y su pueblo fue librado.",
    prayer:
      "Dios de esta hora, dame valor que empiece de rodillas. Si perezco, que perezca — pero iré.",
    difficulty: "balanced",
    category: "people",
  },
  {
    id: "wg-es-rut",
    locale: "es",
    question: "¿Quién dijo: a dondequiera que vayas, iré?",
    answer: "RUT",
    scriptureReference: "Rut 1:16",
    hint: "Una moabita que espigaba en los campos de Booz.",
    explanation: "Rut eligió al pueblo y al Dios de Noemí, y fue bisabuela de David.",
    prayer:
      "Dios de Rut, adonde vayas iré. Haz de mi pequeña fidelidad diaria parte de tu larga historia.",
    difficulty: "gentle",
    category: "people",
  },
  {
    id: "wg-es-elias",
    locale: "es",
    question: "¿Quién fue llevado en un carro de fuego?",
    answer: "ELÍAS",
    scriptureReference: "2 Reyes 2:11",
    hint: "Los cuervos lo alimentaban junto al arroyo.",
    explanation: "Elías subió al cielo en un torbellino, y Eliseo recibió su manto.",
    prayer:
      "Dios del silbo apacible, aliméntame cuando esté agotado. Habla después del viento, y escucharé.",
    difficulty: "challenging",
    category: "people",
  },
  {
    id: "wg-es-goliat",
    locale: "es",
    question: "¿Qué gigante de Gat desafió a los ejércitos de Israel?",
    answer: "GOLIAT",
    scriptureReference: "1 Samuel 17:4–11",
    hint: "Cayó ante la honda de un pastor.",
    explanation:
      "Goliat confió en la armadura y la lanza; David vino en el nombre del Señor de los ejércitos.",
    prayer:
      "Señor de los ejércitos, la batalla es tuya. Enfrento lo que se alza sobre mí con cinco piedras lisas y tu nombre.",
    difficulty: "challenging",
    category: "people",
  },
  {
    id: "wg-es-belen",
    locale: "es",
    question: "¿En qué ciudad nació Jesús?",
    answer: "BELÉN",
    scriptureReference: "Lucas 2:4–7",
    hint: "La ciudad de David, pequeña entre las de Judá.",
    explanation: "En Belén — casa de pan — el Pan de Vida fue acostado en un pesebre.",
    prayer:
      "Pan de Vida, nacido en la casa del pan, nace también en mi lugar pequeño. Ningún pueblo es demasiado pequeño para ti.",
    difficulty: "challenging",
    category: "places",
  },
  {
    id: "wg-es-jerico",
    locale: "es",
    question: "¿De qué ciudad cayeron los muros después de siete días?",
    answer: "JERICÓ",
    scriptureReference: "Josué 6:20",
    hint: "Marcharon, y al séptimo día gritaron.",
    explanation: "Los muros de Jericó cayeron, e Israel tomó la ciudad como el Señor había dicho.",
    prayer:
      "Dios que derriba murallas, seguiré marchando en silencio hasta que digas: gritad. Derriba lo que me deja fuera.",
    difficulty: "challenging",
    category: "places",
  },
  {
    id: "wg-es-lazaro",
    locale: "es",
    question: "¿Quién resucitó después de cuatro días en el sepulcro?",
    answer: "LÁZARO",
    scriptureReference: "Juan 11:43–44",
    hint: "Jesús lloró antes de llamarlo por su nombre.",
    explanation: "Jesús clamó a gran voz, y el que había muerto salió.",
    prayer:
      "Señor que llora y luego llama, habla dentro de mi tumba. Desátame, y que salga a la luz.",
    difficulty: "challenging",
    category: "people",
  },
  {
    id: "wg-es-tomas",
    locale: "es",
    question: "¿Qué discípulo dudó hasta ver?",
    answer: "TOMÁS",
    scriptureReference: "Juan 20:27–28",
    hint: "¡Señor mío, y Dios mío!",
    explanation: "Tomás dudó y luego confesó más plenamente que ningún otro.",
    prayer:
      "Señor mío y Dios mío, responde a mi duda con tus marcas. Dichosos los que creen sin ver — hazme uno de ellos.",
    difficulty: "expert",
    category: "people",
  },
  {
    id: "wg-es-gabriel",
    locale: "es",
    question: "¿Qué ángel anunció a María el nacimiento de Jesús?",
    answer: "GABRIEL",
    scriptureReference: "Lucas 1:26–31",
    hint: "También visitó a Zacarías en el templo.",
    explanation: "Gabriel fue enviado por Dios a Nazaret, a una virgen llamada María.",
    prayer:
      "Dios que envía palabra, encuéntrame donde estoy con noticias de gracia. Nada de lo que dices será imposible.",
    difficulty: "expert",
    category: "people",
  },
  {
    id: "wg-es-arca-de-noe",
    locale: "es",
    question: "¿Qué embarcación llevó a la familia de Noé por el diluvio?",
    answer: "ARCA DE NOÉ",
    scriptureReference: "Génesis 7:1",
    hint: "Hecha de madera de gofer, sellada con brea.",
    explanation: "El arca llevó a salvo a la familia de Noé y a los animales por las aguas.",
    prayer:
      "Dios del pacto, cierra la puerta tras de mí y guárdame en la tormenta. Pon tu arco en mis nubes.",
    difficulty: "expert",
    category: "places",
  },
];

const QUESTIONS_BY_LOCALE: Record<WordGuessLocale, readonly WordGuessQuestion[]> = {
  en: EN_QUESTIONS,
  pt: PT_QUESTIONS,
  es: ES_QUESTIONS,
};

export function wordGuessQuestionsForLocale(locale: WordGuessLocale): readonly WordGuessQuestion[] {
  const set = QUESTIONS_BY_LOCALE[locale];
  return set.length > 0 ? set : QUESTIONS_BY_LOCALE.en;
}
