import type { WordGuessLocale, WordGuessQuestion } from "./types";

// Development content only — typed, local, and deliberately not wired to
// Supabase. The per-locale map is the extension point for future Portuguese
// and Spanish sets; questionsForLocale falls back to English the same way the
// app's t() does, so an empty locale never blanks the screen.

const EN_QUESTIONS: readonly WordGuessQuestion[] = [
  {
    id: "wg-en-moses",
    locale: "en",
    question: "Who parted the Red Sea?",
    answer: "MOSES",
    scriptureReference: "Exodus 14:21–22",
    hint: "He was raised in Pharaoh's palace.",
    explanation: "Moses stretched out his hand, and the Lord divided the sea for Israel to cross.",
    difficulty: "gentle",
    category: "people",
  },
  {
    id: "wg-en-noah",
    locale: "en",
    question: "Who built the ark?",
    answer: "NOAH",
    scriptureReference: "Genesis 6:13–22",
    hint: "It rained for forty days and forty nights.",
    explanation:
      "Noah built the ark in obedience, and his household was kept safe through the flood.",
    difficulty: "gentle",
    category: "people",
  },
  {
    id: "wg-en-david",
    locale: "en",
    question: "Who defeated Goliath?",
    answer: "DAVID",
    scriptureReference: "1 Samuel 17:45–50",
    hint: "A shepherd boy with a sling and five smooth stones.",
    explanation: "David faced the giant in the name of the Lord and prevailed with a single stone.",
    difficulty: "gentle",
    category: "people",
  },
  {
    id: "wg-en-jonah",
    locale: "en",
    question: "Who was swallowed by a great fish?",
    answer: "JONAH",
    scriptureReference: "Jonah 1:17",
    hint: "He ran from a call to Nineveh.",
    explanation:
      "Jonah spent three days and nights inside the fish before being given a second chance.",
    difficulty: "gentle",
    category: "people",
  },
  {
    id: "wg-en-adam",
    locale: "en",
    question: "Who was the first man?",
    answer: "ADAM",
    scriptureReference: "Genesis 2:7",
    hint: "Formed from the dust of the ground.",
    explanation: "Adam was formed from dust and received the breath of life from God.",
    difficulty: "gentle",
    category: "people",
  },
  {
    id: "wg-en-eve",
    locale: "en",
    question: "Who was the first woman?",
    answer: "EVE",
    scriptureReference: "Genesis 3:20",
    hint: 'Her name means "living".',
    explanation: "Eve was called the mother of all living.",
    difficulty: "gentle",
    category: "people",
  },
  {
    id: "wg-en-joseph",
    locale: "en",
    question: "Who interpreted Pharaoh's dreams?",
    answer: "JOSEPH",
    scriptureReference: "Genesis 41:25–36",
    hint: "His brothers sold him, but God meant it for good.",
    explanation: "Joseph read the dreams as seven years of plenty followed by seven of famine.",
    difficulty: "balanced",
    category: "people",
  },
  {
    id: "wg-en-judas",
    locale: "en",
    question: "Who betrayed Jesus?",
    answer: "JUDAS",
    scriptureReference: "Luke 22:47–48",
    hint: "He handed him over with a kiss.",
    explanation: "Judas Iscariot betrayed Jesus to the authorities for thirty pieces of silver.",
    difficulty: "balanced",
    category: "people",
  },
  {
    id: "wg-en-mary",
    locale: "en",
    question: "Who was the mother of Jesus?",
    answer: "MARY",
    scriptureReference: "Luke 1:30–31",
    hint: "The angel Gabriel brought her the news.",
    explanation:
      'Mary received the angel\'s word with faith: "let it be to me according to your word".',
    difficulty: "balanced",
    category: "people",
  },
  {
    id: "wg-en-john",
    locale: "en",
    question: "Who baptized Jesus?",
    answer: "JOHN",
    scriptureReference: "Matthew 3:13–17",
    hint: "A voice crying in the wilderness.",
    explanation: "John baptized Jesus in the Jordan, and the Spirit descended like a dove.",
    difficulty: "balanced",
    category: "people",
  },
  {
    id: "wg-en-peter",
    locale: "en",
    question: "Who denied Jesus three times?",
    answer: "PETER",
    scriptureReference: "Luke 22:60–62",
    hint: "The rooster crowed, and he remembered.",
    explanation:
      "Peter denied his Lord three times, wept bitterly — and was later restored three times.",
    difficulty: "balanced",
    category: "people",
  },
  {
    id: "wg-en-solomon",
    locale: "en",
    question: "Who was known for great wisdom?",
    answer: "SOLOMON",
    scriptureReference: "1 Kings 3:9–12",
    hint: "He asked God for an understanding heart.",
    explanation: "Solomon asked for wisdom rather than riches, and God granted both.",
    difficulty: "challenging",
    category: "people",
  },
  {
    id: "wg-en-daniel",
    locale: "en",
    question: "Who was thrown into the lions' den?",
    answer: "DANIEL",
    scriptureReference: "Daniel 6:16–23",
    hint: "He kept praying three times a day.",
    explanation: "Daniel was delivered unharmed, for he had trusted in his God.",
    difficulty: "challenging",
    category: "people",
  },
  {
    id: "wg-en-joshua",
    locale: "en",
    question: "Who led the Israelites into the Promised Land?",
    answer: "JOSHUA",
    scriptureReference: "Joshua 1:1–9",
    hint: '"Be strong and courageous."',
    explanation: "Joshua succeeded Moses and led Israel across the Jordan into the land.",
    difficulty: "challenging",
    category: "people",
  },
  {
    id: "wg-en-zacchaeus",
    locale: "en",
    question: "Who climbed a tree to see Jesus?",
    answer: "ZACCHAEUS",
    scriptureReference: "Luke 19:1–10",
    hint: "A short tax collector in Jericho.",
    explanation: "Zacchaeus climbed a sycamore tree, and Jesus called him down by name.",
    difficulty: "challenging",
    category: "people",
  },
  {
    id: "wg-en-holy-spirit",
    locale: "en",
    question: "Who descended at Pentecost with tongues of fire?",
    answer: "HOLY SPIRIT",
    scriptureReference: "Acts 2:1–4",
    hint: "The promised Helper.",
    explanation:
      "At Pentecost the Holy Spirit filled the disciples, and they spoke in other tongues.",
    difficulty: "expert",
    category: "events",
  },
  {
    id: "wg-en-mary-magdalene",
    locale: "en",
    question: "Who first saw the risen Jesus at the tomb?",
    answer: "MARY MAGDALENE",
    scriptureReference: "John 20:11–18",
    hint: "She mistook him for the gardener.",
    explanation:
      'Mary Magdalene met the risen Lord in the garden and announced: "I have seen the Lord".',
    difficulty: "expert",
    category: "people",
  },
  {
    id: "wg-en-noahs-ark",
    locale: "en",
    question: "What vessel carried Noah's family through the flood?",
    answer: "NOAH'S ARK",
    scriptureReference: "Genesis 7:1",
    hint: "Built of gopher wood, sealed with pitch.",
    explanation: "The ark carried Noah's family and the animals safely through the waters.",
    difficulty: "expert",
    category: "places",
  },
];

const QUESTIONS_BY_LOCALE: Record<WordGuessLocale, readonly WordGuessQuestion[]> = {
  en: EN_QUESTIONS,
  // Future Portuguese and Spanish sets slot in here; until then the English
  // set is served, mirroring the app-wide t() fallback.
  pt: [],
  es: [],
};

export function wordGuessQuestionsForLocale(locale: WordGuessLocale): readonly WordGuessQuestion[] {
  const set = QUESTIONS_BY_LOCALE[locale];
  return set.length > 0 ? set : QUESTIONS_BY_LOCALE.en;
}
